/**
 * Which divination cards this app can price a flip for, and what each one turns into - generated
 * by scripts/generate-divination-cards.ts from RePoE's base_items.json (the same trusted source
 * scripts/generate-faustus-mapping.ts uses for Faustus's name<->id map). Do not hand-edit; re-run
 * the generator instead.
 *
 * Only cards with a single, deterministic reward are listed here - cards RePoE describes with a
 * randomized outcome (a roll, a random item of a category, a guaranteed-corrupted unique, a
 * Magic/Rare base's randomly-rolled affixes) are excluded by the generator itself, since their
 * true expected value can't be computed from a single number. ONE deliberate simplification, not
 * an exclusion: a Magic/Rare-rarity reward (e.g. "Perandus' Gold Ring", a rare "Six-Link Astral
 * Plate") is priced as if it were just the plain base type, ignoring whatever affixes actually
 * get rolled onto it - the base itself is usually most of a reward like this one's value anyway,
 * and there's no live data source for "this specific rare item with unknown future affixes" to do
 * better than that. This list alone can't yet tell a real reward name ("Mageblood", "Sulphite
 * Scarab") apart from a single-tag placeholder ("Axe", "Item", "League-Specific Item") -
 * lib/divination-flips.ts filters those out at request time by checking whether the reward name
 * actually matches something in today's live price data.
 */
export type DivinationRewardKind = "unique" | "currency" | "card";

export interface DivinationCardDef {
  /** The card's own display name, as poe.ninja/the Currency Exchange price it under. */
  name: string;
  /** Copies needed to turn the card in. */
  stackSize: number;
  rewardKind: DivinationRewardKind;
  /** For "unique": the unique item's name (poe.ninja's UniqueWeapon/UniqueArmour/... overviews).
   *  For "currency": the currency/Scarab/Fragment/base-type's name (poe.ninja's currency
   *  overview) - covers a plain named item with zero randomness (e.g. "Sulphite Scarab") and a
   *  Magic/Rare reward priced as its base type (see this file's module doc), not just literal
   *  currencies. For "card": another card's name (poe.ninja's DivinationCard overview, same map
   *  this card's own price comes from). */
  rewardName: string;
  /** How many of rewardName the turn-in grants - 1 for a unique/card reward, N for most currency
   *  rewards (e.g. "3x Chaos Orb"). */
  rewardQuantity: number;
}

export const DIVINATION_CARDS: readonly DivinationCardDef[] = [
  { name: "A Dab of Ink", stackSize: 9, rewardKind: "unique", rewardName: "The Poet's Pen", rewardQuantity: 1 },
  { name: "A Note in the Wind", stackSize: 4, rewardKind: "unique", rewardName: "Asenath's Mark", rewardQuantity: 1 },
  { name: "A Sea of Blue", stackSize: 3, rewardKind: "currency", rewardName: "Orb of Alteration", rewardQuantity: 13 },
  { name: "Abandoned Wealth", stackSize: 5, rewardKind: "currency", rewardName: "Exalted Orb", rewardQuantity: 3 },
  { name: "Acclimatisation", stackSize: 2, rewardKind: "currency", rewardName: "Orb of Alteration", rewardQuantity: 20 },
  { name: "Alivia's Grace", stackSize: 6, rewardKind: "unique", rewardName: "Queen of the Forest", rewardQuantity: 1 },
  { name: "Alluring Bounty", stackSize: 7, rewardKind: "currency", rewardName: "Exalted Orb", rewardQuantity: 10 },
  { name: "Alone in the Darkness", stackSize: 5, rewardKind: "unique", rewardName: "Delve Item", rewardQuantity: 1 },
  { name: "Altered Perception", stackSize: 3, rewardKind: "currency", rewardName: "Simulacrum", rewardQuantity: 1 },
  { name: "Ambitious Obsession", stackSize: 4, rewardKind: "currency", rewardName: "Skittering Delirium Orb", rewardQuantity: 1 },
  { name: "Assassin's Favour", stackSize: 9, rewardKind: "unique", rewardName: "Dagger", rewardQuantity: 1 },
  { name: "Avian Pursuit", stackSize: 3, rewardKind: "currency", rewardName: "Vivid Crystallised Lifeforce", rewardQuantity: 1500 },
  { name: "Baited Expectations", stackSize: 8, rewardKind: "unique", rewardName: "Fishing Item", rewardQuantity: 1 },
  { name: "Beauty Through Death", stackSize: 5, rewardKind: "unique", rewardName: "Atziri's Reflection", rewardQuantity: 1 },
  { name: "Birth of the Three", stackSize: 3, rewardKind: "unique", rewardName: "The Goddess Bound", rewardQuantity: 1 },
  { name: "Boon of Justice", stackSize: 6, rewardKind: "currency", rewardName: "Offering to the Goddess", rewardQuantity: 1 },
  { name: "Boon of the First Ones", stackSize: 6, rewardKind: "unique", rewardName: "Bestiary Item", rewardQuantity: 1 },
  { name: "Boundless Realms", stackSize: 4, rewardKind: "currency", rewardName: "Map", rewardQuantity: 1 },
  { name: "Broken Truce", stackSize: 5, rewardKind: "unique", rewardName: "Cold Iron Point", rewardQuantity: 1 },
  { name: "Brother's Gift", stackSize: 1, rewardKind: "currency", rewardName: "Divine Orb", rewardQuantity: 5 },
  { name: "Brother's Stash", stackSize: 1, rewardKind: "currency", rewardName: "Exalted Orb", rewardQuantity: 5 },
  { name: "Brush, Paint and Palette", stackSize: 5, rewardKind: "card", rewardName: "The Artist", rewardQuantity: 1 },
  { name: "Buried Treasure", stackSize: 3, rewardKind: "currency", rewardName: "Sulphite Scarab", rewardQuantity: 1 },
  { name: "Call to the First Ones", stackSize: 5, rewardKind: "currency", rewardName: "Talisman", rewardQuantity: 1 },
  { name: "Cameria's Cut", stackSize: 2, rewardKind: "currency", rewardName: "Scarab", rewardQuantity: 1 },
  { name: "Chaotic Disposition", stackSize: 1, rewardKind: "currency", rewardName: "Chaos Orb", rewardQuantity: 5 },
  { name: "Chasing Risk", stackSize: 4, rewardKind: "unique", rewardName: "Synthesis Item", rewardQuantity: 1 },
  { name: "Checkmate", stackSize: 8, rewardKind: "currency", rewardName: "Simulacrum Splinter", rewardQuantity: 76 },
  { name: "Choking Guilt", stackSize: 6, rewardKind: "unique", rewardName: "Stranglegasp", rewardQuantity: 1 },
  { name: "Council of Cats", stackSize: 4, rewardKind: "unique", rewardName: "Farrul Item", rewardQuantity: 1 },
  { name: "Coveted Possession", stackSize: 9, rewardKind: "currency", rewardName: "Regal Orb", rewardQuantity: 5 },
  { name: "Cursed Words", stackSize: 13, rewardKind: "unique", rewardName: "Maw of Mischief", rewardQuantity: 1 },
  { name: "Dark Temptation", stackSize: 5, rewardKind: "unique", rewardName: "Obliteration", rewardQuantity: 1 },
  { name: "Darker Half", stackSize: 3, rewardKind: "currency", rewardName: "Eldritch Chaos Orb", rewardQuantity: 5 },
  { name: "Death", stackSize: 4, rewardKind: "unique", rewardName: "Mon'tregul's Grasp", rewardQuantity: 1 },
  { name: "Dementophobia", stackSize: 11, rewardKind: "currency", rewardName: "Delirium Orb", rewardQuantity: 10 },
  { name: "Demigod's Wager", stackSize: 7, rewardKind: "currency", rewardName: "Orb of Annulment", rewardQuantity: 1 },
  { name: "Desperate Crusade", stackSize: 3, rewardKind: "unique", rewardName: "Prism Guardian", rewardQuantity: 1 },
  { name: "Disdain", stackSize: 5, rewardKind: "currency", rewardName: "Delirium Orb", rewardQuantity: 1 },
  { name: "Divine Beauty", stackSize: 12, rewardKind: "currency", rewardName: "Divine Orb", rewardQuantity: 7 },
  { name: "Divine Shard", stackSize: 2, rewardKind: "currency", rewardName: "Divine Vessel", rewardQuantity: 1 },
  { name: "Doedre's Madness", stackSize: 9, rewardKind: "unique", rewardName: "Doedre Item", rewardQuantity: 1 },
  { name: "Earth Drinker", stackSize: 5, rewardKind: "unique", rewardName: "Granite Flask", rewardQuantity: 1 },
  { name: "Emperor's Luck", stackSize: 5, rewardKind: "currency", rewardName: "Currency", rewardQuantity: 5 },
  { name: "Endless Night", stackSize: 7, rewardKind: "unique", rewardName: "Maloney's Mechanism", rewardQuantity: 1 },
  { name: "Energy Sword", stackSize: 3, rewardKind: "unique", rewardName: "Ephemeral Edge", rewardQuantity: 1 },
  { name: "Eternal Bonds", stackSize: 4, rewardKind: "unique", rewardName: "Replica Cortex", rewardQuantity: 1 },
  { name: "Ever-Changing", stackSize: 3, rewardKind: "currency", rewardName: "Orb of Unmaking", rewardQuantity: 10 },
  { name: "Father's Love", stackSize: 2, rewardKind: "unique", rewardName: "Sublime Vision", rewardQuantity: 1 },
  { name: "Fire Of Unknown Origin", stackSize: 7, rewardKind: "unique", rewardName: "Nimis", rewardQuantity: 1 },
  { name: "Friendship", stackSize: 3, rewardKind: "unique", rewardName: "Aul's Uprising", rewardQuantity: 1 },
  { name: "Glimmer of Hope", stackSize: 8, rewardKind: "unique", rewardName: "Gold Ring", rewardQuantity: 1 },
  { name: "Guardian's Challenge", stackSize: 4, rewardKind: "currency", rewardName: "Shaper Guardian Map", rewardQuantity: 1 },
  { name: "Harmony of Souls", stackSize: 9, rewardKind: "currency", rewardName: "Shrieking Essence", rewardQuantity: 9 },
  { name: "Haunting Shadows", stackSize: 4, rewardKind: "unique", rewardName: "Metamorph Item", rewardQuantity: 1 },
  { name: "Her Mask", stackSize: 4, rewardKind: "currency", rewardName: "Sacrifice Fragment", rewardQuantity: 1 },
  { name: "Heterochromia", stackSize: 2, rewardKind: "unique", rewardName: "Two-Stone Ring", rewardQuantity: 1 },
  { name: "History", stackSize: 5, rewardKind: "currency", rewardName: "Hinekora's Lock", rewardQuantity: 2 },
  { name: "House of Mirrors", stackSize: 9, rewardKind: "currency", rewardName: "Mirror of Kalandra", rewardQuantity: 1 },
  { name: "Hubris", stackSize: 5, rewardKind: "unique", rewardName: "Ring", rewardQuantity: 1 },
  { name: "Humility", stackSize: 9, rewardKind: "unique", rewardName: "Tabula Rasa", rewardQuantity: 1 },
  { name: "Hunter's Resolve", stackSize: 8, rewardKind: "unique", rewardName: "Bow", rewardQuantity: 1 },
  { name: "Hunter's Reward", stackSize: 3, rewardKind: "unique", rewardName: "The Taming", rewardQuantity: 1 },
  { name: "I See Brothers", stackSize: 2, rewardKind: "currency", rewardName: "Fracturing Orb", rewardQuantity: 2 },
  { name: "Imperfect Memories", stackSize: 5, rewardKind: "currency", rewardName: "Astrolabe", rewardQuantity: 1 },
  { name: "Jack in the Box", stackSize: 4, rewardKind: "unique", rewardName: "Item", rewardQuantity: 1 },
  { name: "Judging Voices", stackSize: 9, rewardKind: "unique", rewardName: "Forbidden Shako", rewardQuantity: 1 },
  { name: "Justified Ambition", stackSize: 5, rewardKind: "unique", rewardName: "Synthesis Map", rewardQuantity: 1 },
  { name: "Lantador's Lost Love", stackSize: 7, rewardKind: "currency", rewardName: "Two-Stone Ring", rewardQuantity: 1 },
  { name: "Last Hope", stackSize: 3, rewardKind: "currency", rewardName: "Mortal Hope", rewardQuantity: 1 },
  { name: "Last Stand", stackSize: 3, rewardKind: "unique", rewardName: "The Surrender", rewardQuantity: 1 },
  { name: "Lethean Temptation", stackSize: 6, rewardKind: "unique", rewardName: "Nebulis", rewardQuantity: 1 },
  { name: "Light and Truth", stackSize: 2, rewardKind: "unique", rewardName: "Crystal Sceptre", rewardQuantity: 1 },
  { name: "Lonely Warrior", stackSize: 10, rewardKind: "unique", rewardName: "Defiance of Destiny", rewardQuantity: 1 },
  { name: "Loyalty", stackSize: 5, rewardKind: "currency", rewardName: "Orb of Fusing", rewardQuantity: 3 },
  { name: "Lucky Bastion", stackSize: 6, rewardKind: "unique", rewardName: "Svalinn", rewardQuantity: 1 },
  { name: "Lucky Connections", stackSize: 7, rewardKind: "currency", rewardName: "Orb of Fusing", rewardQuantity: 20 },
  { name: "Lucky Deck", stackSize: 9, rewardKind: "currency", rewardName: "Stacked Deck", rewardQuantity: 10 },
  { name: "Man With Bear", stackSize: 3, rewardKind: "currency", rewardName: "Bestiary Scarab", rewardQuantity: 1 },
  { name: "Mawr Blaidd", stackSize: 16, rewardKind: "unique", rewardName: "Eyes of the Greatwolf", rewardQuantity: 1 },
  { name: "Might is Right", stackSize: 9, rewardKind: "unique", rewardName: "Trypanon", rewardQuantity: 1 },
  { name: "Misery in Darkness", stackSize: 6, rewardKind: "unique", rewardName: "Shroud of the Lightless", rewardQuantity: 1 },
  { name: "Mitts", stackSize: 5, rewardKind: "unique", rewardName: "Gloves", rewardQuantity: 1 },
  { name: "Monochrome", stackSize: 3, rewardKind: "currency", rewardName: "Valdo's Puzzle Box", rewardQuantity: 1 },
  { name: "More is Never Enough", stackSize: 7, rewardKind: "currency", rewardName: "Scarab", rewardQuantity: 4 },
  { name: "No Traces", stackSize: 9, rewardKind: "currency", rewardName: "Orb of Scouring", rewardQuantity: 30 },
  { name: "Outfoxed", stackSize: 2, rewardKind: "currency", rewardName: "Veiled Exalted Orb", rewardQuantity: 1 },
  { name: "Peaceful Moments", stackSize: 5, rewardKind: "unique", rewardName: "Timeless Jewel", rewardQuantity: 1 },
  { name: "Pearls Before Swine", stackSize: 3, rewardKind: "unique", rewardName: "Progenesis", rewardQuantity: 1 },
  { name: "Pride of the First Ones", stackSize: 7, rewardKind: "unique", rewardName: "Farrul's Fur", rewardQuantity: 1 },
  { name: "Prosperity", stackSize: 10, rewardKind: "currency", rewardName: "Perandus' Gold Ring", rewardQuantity: 1 },
  { name: "Rain of Chaos", stackSize: 8, rewardKind: "currency", rewardName: "Chaos Orb", rewardQuantity: 1 },
  { name: "Rats", stackSize: 8, rewardKind: "unique", rewardName: "Rat's Nest", rewardQuantity: 1 },
  { name: "Rebirth", stackSize: 27, rewardKind: "unique", rewardName: "Charan's Sword", rewardQuantity: 1 },
  { name: "Rebirth and Renewal", stackSize: 4, rewardKind: "currency", rewardName: "Horned Scarab", rewardQuantity: 1 },
  { name: "Reckless Ambition", stackSize: 6, rewardKind: "unique", rewardName: "Omeyocan", rewardQuantity: 1 },
  { name: "Reflection of the Heart", stackSize: 2, rewardKind: "unique", rewardName: "Kalandra's Touch", rewardQuantity: 1 },
  { name: "Runic Luck", stackSize: 4, rewardKind: "currency", rewardName: "Vendor Refresh Currency", rewardQuantity: 10 },
  { name: "Sambodhi's Vow", stackSize: 3, rewardKind: "currency", rewardName: "Mortal Fragment", rewardQuantity: 1 },
  { name: "Scholar of the Seas", stackSize: 7, rewardKind: "unique", rewardName: "Mao Kun", rewardQuantity: 1 },
  { name: "Seven Years Bad Luck", stackSize: 13, rewardKind: "currency", rewardName: "Mirror Shard", rewardQuantity: 1 },
  { name: "Shard of Fate", stackSize: 4, rewardKind: "currency", rewardName: "Vivid Jewel", rewardQuantity: 1 },
  { name: "Silence and Frost", stackSize: 7, rewardKind: "unique", rewardName: "The Pandemonius", rewardQuantity: 1 },
  { name: "Society's Remorse", stackSize: 1, rewardKind: "currency", rewardName: "Orb of Alteration", rewardQuantity: 10 },
  { name: "Succor of the Sinless", stackSize: 6, rewardKind: "unique", rewardName: "Bottled Faith", rewardQuantity: 1 },
  { name: "The Academic", stackSize: 8, rewardKind: "unique", rewardName: "Inspired Learning", rewardQuantity: 1 },
  { name: "The Admirer", stackSize: 9, rewardKind: "unique", rewardName: "Atziri Item", rewardQuantity: 1 },
  { name: "The Adventuring Spirit", stackSize: 6, rewardKind: "unique", rewardName: "Victario's Influence", rewardQuantity: 1 },
  { name: "The Aesthete", stackSize: 8, rewardKind: "unique", rewardName: "Shavronne Item", rewardQuantity: 1 },
  { name: "The Apothecary", stackSize: 5, rewardKind: "unique", rewardName: "Mageblood", rewardQuantity: 1 },
  { name: "The Army of Blood", stackSize: 6, rewardKind: "unique", rewardName: "Bloodbond", rewardQuantity: 1 },
  { name: "The Battle Born", stackSize: 5, rewardKind: "unique", rewardName: "Axe", rewardQuantity: 1 },
  { name: "The Beast", stackSize: 6, rewardKind: "unique", rewardName: "Belly of the Beast", rewardQuantity: 1 },
  { name: "The Betrayal", stackSize: 9, rewardKind: "unique", rewardName: "Maligaro's Virtuosity", rewardQuantity: 1 },
  { name: "The Blazing Fire", stackSize: 6, rewardKind: "unique", rewardName: "Chin Sol", rewardQuantity: 1 },
  { name: "The Body", stackSize: 4, rewardKind: "unique", rewardName: "Body Armour", rewardQuantity: 1 },
  { name: "The Breach", stackSize: 4, rewardKind: "unique", rewardName: "Breach Item", rewardQuantity: 1 },
  { name: "The Cache", stackSize: 6, rewardKind: "unique", rewardName: "Jewellery", rewardQuantity: 1 },
  { name: "The Cacophony", stackSize: 8, rewardKind: "currency", rewardName: "Deafening Essence", rewardQuantity: 3 },
  { name: "The Calling", stackSize: 6, rewardKind: "unique", rewardName: "Beyond Item", rewardQuantity: 1 },
  { name: "The Card Sharp", stackSize: 4, rewardKind: "currency", rewardName: "Divination Scarab", rewardQuantity: 1 },
  { name: "The Carrion Crow", stackSize: 4, rewardKind: "currency", rewardName: "Life Armour", rewardQuantity: 1 },
  { name: "The Catalyst", stackSize: 3, rewardKind: "currency", rewardName: "Vaal Orb", rewardQuantity: 1 },
  { name: "The Celestial Justicar", stackSize: 6, rewardKind: "currency", rewardName: "Six-Link Astral Plate", rewardQuantity: 1 },
  { name: "The Chains that Bind", stackSize: 11, rewardKind: "currency", rewardName: "Six-Link Body Armour", rewardQuantity: 1 },
  { name: "The Coming Storm", stackSize: 8, rewardKind: "unique", rewardName: "Lightning Coil", rewardQuantity: 1 },
  { name: "The Conduit", stackSize: 9, rewardKind: "unique", rewardName: "Doryani's Fist", rewardQuantity: 1 },
  { name: "The Craving", stackSize: 4, rewardKind: "unique", rewardName: "Unending Hunger", rewardQuantity: 1 },
  { name: "The Cursed King", stackSize: 8, rewardKind: "unique", rewardName: "Rigwald's Curse", rewardQuantity: 1 },
  { name: "The Damned", stackSize: 6, rewardKind: "unique", rewardName: "Soul Ripper", rewardQuantity: 1 },
  { name: "The Deal", stackSize: 5, rewardKind: "currency", rewardName: "Cartography Scarab", rewardQuantity: 1 },
  { name: "The Deep Ones", stackSize: 5, rewardKind: "unique", rewardName: "Tidebreaker", rewardQuantity: 1 },
  { name: "The Demoness", stackSize: 5, rewardKind: "unique", rewardName: "Death's Hand", rewardQuantity: 1 },
  { name: "The Doctor", stackSize: 8, rewardKind: "unique", rewardName: "Headhunter", rewardQuantity: 1 },
  { name: "The Dragon", stackSize: 4, rewardKind: "unique", rewardName: "Coruscating Elixir", rewardQuantity: 1 },
  { name: "The Dreamer", stackSize: 6, rewardKind: "unique", rewardName: "Chayula Item", rewardQuantity: 1 },
  { name: "The Dreamland", stackSize: 8, rewardKind: "unique", rewardName: "Poorjoy's Asylum", rewardQuantity: 1 },
  { name: "The Drunken Aristocrat", stackSize: 8, rewardKind: "unique", rewardName: "Divination Distillate", rewardQuantity: 1 },
  { name: "The Eldritch Decay", stackSize: 4, rewardKind: "currency", rewardName: "Uber Elder Fragment", rewardQuantity: 1 },
  { name: "The Endless Darkness", stackSize: 9, rewardKind: "unique", rewardName: "Voidforge", rewardQuantity: 1 },
  { name: "The Endurance", stackSize: 4, rewardKind: "currency", rewardName: "Vivid Crimson Jewel", rewardQuantity: 1 },
  { name: "The Escape", stackSize: 5, rewardKind: "unique", rewardName: "Seven-League Step", rewardQuantity: 1 },
  { name: "The Ethereal", stackSize: 7, rewardKind: "currency", rewardName: "Six-Link Vaal Regalia", rewardQuantity: 1 },
  { name: "The Everlasting", stackSize: 3, rewardKind: "unique", rewardName: "Originator Incarnation Item", rewardQuantity: 1 },
  { name: "The Eye of Terror", stackSize: 8, rewardKind: "unique", rewardName: "Mageblood", rewardQuantity: 1 },
  { name: "The Fathomless Depths", stackSize: 8, rewardKind: "unique", rewardName: "Lightpoacher", rewardQuantity: 1 },
  { name: "The Finishing Touch", stackSize: 2, rewardKind: "currency", rewardName: "Fertile Catalyst", rewardQuantity: 1 },
  { name: "The Fishmonger", stackSize: 4, rewardKind: "currency", rewardName: "Albino Rhoa Feather", rewardQuantity: 1 },
  { name: "The Fool", stackSize: 4, rewardKind: "currency", rewardName: "Orb of Chance", rewardQuantity: 20 },
  { name: "The Forbidden Fruit", stackSize: 1, rewardKind: "currency", rewardName: "Uber Pinnacle Fragment", rewardQuantity: 1 },
  { name: "The Formless Sea", stackSize: 7, rewardKind: "unique", rewardName: "Varunastra", rewardQuantity: 1 },
  { name: "The Forsaken", stackSize: 7, rewardKind: "unique", rewardName: "Umbilicus Immortalis", rewardQuantity: 1 },
  { name: "The Fortunate", stackSize: 12, rewardKind: "currency", rewardName: "Divine Orb", rewardQuantity: 2 },
  { name: "The Forward Gaze", stackSize: 6, rewardKind: "unique", rewardName: "Replica Item", rewardQuantity: 1 },
  { name: "The Gambler", stackSize: 5, rewardKind: "card", rewardName: "Divination Card", rewardQuantity: 1 },
  { name: "The Garish Power", stackSize: 4, rewardKind: "unique", rewardName: "Jewel", rewardQuantity: 1 },
  { name: "The Gemcutter", stackSize: 3, rewardKind: "currency", rewardName: "Gemcutter's Prism", rewardQuantity: 1 },
  { name: "The Gladiator", stackSize: 5, rewardKind: "unique", rewardName: "Nightmare Bascinet", rewardQuantity: 1 },
  { name: "The Harvester", stackSize: 11, rewardKind: "unique", rewardName: "The Harvest", rewardQuantity: 1 },
  { name: "The Hermit", stackSize: 9, rewardKind: "unique", rewardName: "Lifesprig", rewardQuantity: 1 },
  { name: "The Heroic Shot", stackSize: 1, rewardKind: "currency", rewardName: "Chromatic Orb", rewardQuantity: 17 },
  { name: "The Hoarder", stackSize: 12, rewardKind: "currency", rewardName: "Exalted Orb", rewardQuantity: 1 },
  { name: "The Hunger", stackSize: 9, rewardKind: "unique", rewardName: "Taste of Hate", rewardQuantity: 1 },
  { name: "The Immortal", stackSize: 10, rewardKind: "card", rewardName: "House of Mirrors", rewardQuantity: 1 },
  { name: "The Incantation", stackSize: 4, rewardKind: "unique", rewardName: "The Whispering Ice", rewardQuantity: 1 },
  { name: "The Innocent", stackSize: 10, rewardKind: "currency", rewardName: "Orb of Regret", rewardQuantity: 40 },
  { name: "The Inoculated", stackSize: 4, rewardKind: "currency", rewardName: "Seraphim's Armour", rewardQuantity: 1 },
  { name: "The Inventor", stackSize: 6, rewardKind: "currency", rewardName: "Vaal Orb", rewardQuantity: 10 },
  { name: "The Journey", stackSize: 4, rewardKind: "currency", rewardName: "Journey Tattoo", rewardQuantity: 1 },
  { name: "The King's Heart", stackSize: 8, rewardKind: "unique", rewardName: "Kaom's Heart", rewardQuantity: 1 },
  { name: "The Lake", stackSize: 8, rewardKind: "currency", rewardName: "Reflecting Mist", rewardQuantity: 1 },
  { name: "The Last One Standing", stackSize: 10, rewardKind: "unique", rewardName: "Atziri's Disfavour", rewardQuantity: 1 },
  { name: "The Last Supper", stackSize: 6, rewardKind: "unique", rewardName: "Bino's Kitchen Knife", rewardQuantity: 1 },
  { name: "The Life Thief", stackSize: 6, rewardKind: "unique", rewardName: "Zerphi's Heart", rewardQuantity: 1 },
  { name: "The Lion", stackSize: 5, rewardKind: "unique", rewardName: "Lioneye Item", rewardQuantity: 1 },
  { name: "The Long Con", stackSize: 4, rewardKind: "currency", rewardName: "Elderslayer's Exalted Orb", rewardQuantity: 1 },
  { name: "The Long Watch", stackSize: 3, rewardKind: "unique", rewardName: "The Fourth Vow", rewardQuantity: 1 },
  { name: "The Lunaris Priestess", stackSize: 5, rewardKind: "unique", rewardName: "Sire of Shards", rewardQuantity: 1 },
  { name: "The Mad King", stackSize: 7, rewardKind: "unique", rewardName: "Vaal Aspect", rewardQuantity: 1 },
  { name: "The Master Artisan", stackSize: 5, rewardKind: "currency", rewardName: "Quality Currency", rewardQuantity: 20 },
  { name: "The Mayor", stackSize: 5, rewardKind: "unique", rewardName: "The Light of Meaning", rewardQuantity: 1 },
  { name: "The Messenger", stackSize: 4, rewardKind: "unique", rewardName: "Harbinger Item", rewardQuantity: 1 },
  { name: "The Metalsmith's Gift", stackSize: 6, rewardKind: "currency", rewardName: "Prismatic Ring", rewardQuantity: 1 },
  { name: "The Mind's Eyes", stackSize: 7, rewardKind: "unique", rewardName: "Astral Projector", rewardQuantity: 1 },
  { name: "The Mountain", stackSize: 6, rewardKind: "currency", rewardName: "Jewel of Potency", rewardQuantity: 1 },
  { name: "The Nurse", stackSize: 8, rewardKind: "card", rewardName: "The Doctor", rewardQuantity: 1 },
  { name: "The Oath", stackSize: 6, rewardKind: "unique", rewardName: "Death's Oath", rewardQuantity: 1 },
  { name: "The Offering", stackSize: 8, rewardKind: "unique", rewardName: "Shavronne's Wrappings", rewardQuantity: 1 },
  { name: "The Offspring", stackSize: 9, rewardKind: "unique", rewardName: "Ryslatha's Coil", rewardQuantity: 1 },
  { name: "The One That Got Away", stackSize: 7, rewardKind: "unique", rewardName: "Replica Bated Breath", rewardQuantity: 1 },
  { name: "The Pack Leader", stackSize: 6, rewardKind: "unique", rewardName: "Alpha's Howl", rewardQuantity: 1 },
  { name: "The Pact", stackSize: 9, rewardKind: "unique", rewardName: "Pledge of Hands", rewardQuantity: 1 },
  { name: "The Patient", stackSize: 8, rewardKind: "card", rewardName: "The Nurse", rewardQuantity: 1 },
  { name: "The Penitent", stackSize: 5, rewardKind: "unique", rewardName: "Unset Ring", rewardQuantity: 1 },
  { name: "The Polymath", stackSize: 3, rewardKind: "unique", rewardName: "Astramentis", rewardQuantity: 1 },
  { name: "The Prince of Darkness", stackSize: 6, rewardKind: "unique", rewardName: "Elegant Hubris", rewardQuantity: 1 },
  { name: "The Professor", stackSize: 4, rewardKind: "unique", rewardName: "The Putrid Cloister", rewardQuantity: 1 },
  { name: "The Progeny of Lunaris", stackSize: 2, rewardKind: "unique", rewardName: "Dying Sun", rewardQuantity: 1 },
  { name: "The Queen", stackSize: 16, rewardKind: "unique", rewardName: "Atziri's Acuity", rewardQuantity: 1 },
  { name: "The Rabbit's Foot", stackSize: 8, rewardKind: "currency", rewardName: "Incursion Vial", rewardQuantity: 10 },
  { name: "The Return of the Rat", stackSize: 3, rewardKind: "unique", rewardName: "Tavukai", rewardQuantity: 1 },
  { name: "The Risk", stackSize: 3, rewardKind: "unique", rewardName: "Ventor's Gamble", rewardQuantity: 1 },
  { name: "The Rusted Bard", stackSize: 9, rewardKind: "currency", rewardName: "Tainted Mythic Orb", rewardQuantity: 4 },
  { name: "The Saint's Treasure", stackSize: 10, rewardKind: "currency", rewardName: "Exalted Orb", rewardQuantity: 2 },
  { name: "The Samurai's Eye", stackSize: 3, rewardKind: "unique", rewardName: "Watcher's Eye", rewardQuantity: 1 },
  { name: "The Scarred Meadow", stackSize: 9, rewardKind: "unique", rewardName: "Wake of Destruction", rewardQuantity: 1 },
  { name: "The Scavenger", stackSize: 8, rewardKind: "unique", rewardName: "Carcass Jack", rewardQuantity: 1 },
  { name: "The Scholar", stackSize: 3, rewardKind: "currency", rewardName: "Scroll of Wisdom", rewardQuantity: 40 },
  { name: "The Scout", stackSize: 8, rewardKind: "currency", rewardName: "Exalted Orb", rewardQuantity: 7 },
  { name: "The Seeker", stackSize: 9, rewardKind: "currency", rewardName: "Orb of Annulment", rewardQuantity: 3 },
  { name: "The Sephirot", stackSize: 11, rewardKind: "currency", rewardName: "Divine Orb", rewardQuantity: 10 },
  { name: "The Shieldbearer", stackSize: 8, rewardKind: "unique", rewardName: "The Squire", rewardQuantity: 1 },
  { name: "The Side Quest", stackSize: 5, rewardKind: "currency", rewardName: "Incarnation Echo", rewardQuantity: 1 },
  { name: "The Sigil", stackSize: 3, rewardKind: "currency", rewardName: "Unassailable Amulet", rewardQuantity: 1 },
  { name: "The Silly Boy", stackSize: 9, rewardKind: "currency", rewardName: "Horned Scarab", rewardQuantity: 6 },
  { name: "The Slumbering Beast", stackSize: 5, rewardKind: "currency", rewardName: "Hinekora's Lock", rewardQuantity: 1 },
  { name: "The Soul", stackSize: 9, rewardKind: "unique", rewardName: "Soul Taker", rewardQuantity: 1 },
  { name: "The Spark and the Flame", stackSize: 2, rewardKind: "unique", rewardName: "Berek's Respite", rewardQuantity: 1 },
  { name: "The Standoff", stackSize: 3, rewardKind: "unique", rewardName: "Rustic Sash", rewardQuantity: 1 },
  { name: "The Stormcaller", stackSize: 4, rewardKind: "unique", rewardName: "Agnerod Staff", rewardQuantity: 1 },
  { name: "The Sun", stackSize: 7, rewardKind: "unique", rewardName: "Rise of the Phoenix", rewardQuantity: 1 },
  { name: "The Surgeon", stackSize: 4, rewardKind: "currency", rewardName: "Surgeon's Flask", rewardQuantity: 1 },
  { name: "The Survivalist", stackSize: 3, rewardKind: "currency", rewardName: "Orb of Alchemy", rewardQuantity: 7 },
  { name: "The Sword King's Salute", stackSize: 7, rewardKind: "unique", rewardName: "Daresso's Salute", rewardQuantity: 1 },
  { name: "The Tinkerer's Table", stackSize: 5, rewardKind: "currency", rewardName: "Fossil", rewardQuantity: 5 },
  { name: "The Tireless Extractor", stackSize: 8, rewardKind: "currency", rewardName: "Oil", rewardQuantity: 10 },
  { name: "The Tower", stackSize: 6, rewardKind: "unique", rewardName: "Staff", rewardQuantity: 1 },
  { name: "The Transformation", stackSize: 5, rewardKind: "currency", rewardName: "Tainted Mythic Orb", rewardQuantity: 1 },
  { name: "The Twilight Moon", stackSize: 6, rewardKind: "unique", rewardName: "The Twilight Temple", rewardQuantity: 1 },
  { name: "The Union", stackSize: 7, rewardKind: "currency", rewardName: "Gemcutter's Prism", rewardQuantity: 10 },
  { name: "The Valkyrie", stackSize: 8, rewardKind: "unique", rewardName: "Nemesis Item", rewardQuantity: 1 },
  { name: "The Vast", stackSize: 7, rewardKind: "unique", rewardName: "Song of the Sirens", rewardQuantity: 1 },
  { name: "The Visionary", stackSize: 6, rewardKind: "unique", rewardName: "Lioneye's Vision", rewardQuantity: 1 },
  { name: "The Watcher", stackSize: 12, rewardKind: "unique", rewardName: "Crown of Eyes", rewardQuantity: 1 },
  { name: "The Web", stackSize: 8, rewardKind: "currency", rewardName: "Weapon of Crafting", rewardQuantity: 1 },
  { name: "The Wedding Gift", stackSize: 2, rewardKind: "unique", rewardName: "Arakaali's Fang", rewardQuantity: 1 },
  { name: "The Whiteout", stackSize: 8, rewardKind: "unique", rewardName: "Cospri's Malice", rewardQuantity: 1 },
  { name: "The Wind", stackSize: 7, rewardKind: "unique", rewardName: "Windripper", rewardQuantity: 1 },
  { name: "The Witch", stackSize: 8, rewardKind: "unique", rewardName: "Kiara's Determination", rewardQuantity: 1 },
  { name: "The Wolf", stackSize: 5, rewardKind: "unique", rewardName: "Rigwald Item", rewardQuantity: 1 },
  { name: "The Wolf's Legacy", stackSize: 4, rewardKind: "unique", rewardName: "Vaults of Atziri", rewardQuantity: 1 },
  { name: "The Wolf's Shadow", stackSize: 3, rewardKind: "unique", rewardName: "Hyaon's Fury", rewardQuantity: 1 },
  { name: "The Wolven King's Bite", stackSize: 8, rewardKind: "unique", rewardName: "Rigwald's Quills", rewardQuantity: 1 },
  { name: "The World Eater", stackSize: 8, rewardKind: "unique", rewardName: "Starforge", rewardQuantity: 1 },
  { name: "The Wrath", stackSize: 8, rewardKind: "currency", rewardName: "Chaos Orb", rewardQuantity: 10 },
  { name: "The Wretched", stackSize: 6, rewardKind: "unique", rewardName: "Belt", rewardQuantity: 1 },
  { name: "Thirst for Knowledge", stackSize: 5, rewardKind: "unique", rewardName: "Gluttony", rewardQuantity: 1 },
  { name: "Three Faces in the Dark", stackSize: 7, rewardKind: "currency", rewardName: "Chaos Orb", rewardQuantity: 3 },
  { name: "Three Voices", stackSize: 3, rewardKind: "currency", rewardName: "Essence", rewardQuantity: 3 },
  { name: "Thunderous Skies", stackSize: 5, rewardKind: "unique", rewardName: "Storm Cloud", rewardQuantity: 1 },
  { name: "Time-Lost Relic", stackSize: 10, rewardKind: "unique", rewardName: "League-Specific Item", rewardQuantity: 1 },
  { name: "Tranquillity", stackSize: 7, rewardKind: "unique", rewardName: "Voltaxic Rift", rewardQuantity: 1 },
  { name: "Underground Forest", stackSize: 4, rewardKind: "currency", rewardName: "Grand Eldritch Ichor", rewardQuantity: 10 },
  { name: "Unrequited Love", stackSize: 16, rewardKind: "currency", rewardName: "Mirror Shard", rewardQuantity: 19 },
  { name: "Vile Power", stackSize: 5, rewardKind: "unique", rewardName: "Doomfletch", rewardQuantity: 1 },
  { name: "Vinia's Token", stackSize: 5, rewardKind: "currency", rewardName: "Orb of Regret", rewardQuantity: 10 },
] as const;
