/**
 * GGG's official Currency Exchange (the in-game "Faustus" NPC) trade-history API - a real, public,
 * no-auth endpoint (https://web.poecdn.com/api/currency-exchange), confirmed by GGG's own developer
 * docs and by pulling live data during development. Used as a fallback "now" price for the flip
 * suggestions table when poe.ninja hasn't listed an item yet (a real gap for a brand-new or
 * low-volume item early in a league) - poe.ninja's own live-price scrape stays the primary source
 * everywhere; this only fills a hole poe.ninja itself leaves.
 *
 * The one hard problem: the endpoint identifies every item by GGG's internal game-file path (e.g.
 * "Metadata/Items/Currency/CurrencyRerollRare" for Chaos Orb), never a display name, and GGG's own
 * name-lookup endpoint (the trade site's static data) is Cloudflare-blocked without an approved
 * OAuth application - not a quick add. Two earlier attempts at closing that gap didn't hold up:
 * correlating GGG's computed exchange rate against poe.ninja's closest-priced currency was far too
 * unreliable (hundreds of items share a similar price at any hour - produced obviously wrong
 * pairings like Glassblower's Bauble matched to an unrelated Heist currency worth the same that
 * hour), and deriving a name from an id's own structure worked for self-describing categories
 * (Divination Cards, Essences) but broke down for Scarabs specifically - several genuinely
 * different, differently-priced tiers within one mechanic (e.g. "Anarchy Scarab" vs "Anarchy Scarab
 * of Gigantification") derived to the same generic name and validated as false positives.
 *
 * The map below instead comes from RePoE (https://github.com/repoe-fork/repoe), an actively-
 * maintained community mirror of PoE's own game files - unofficial, but a direct machine-file dump
 * rather than a guess, and it resolves every id to its real display name directly, collision-free.
 * scripts/generate-faustus-mapping.ts is the generator - re-run it whenever a new league adds
 * Currency Exchange-tradeable items this map should pick up. Scoped to ids GGG's live exchange
 * actually had open markets for at generation time, so this only ever contains genuinely tradeable
 * items. Unique items (e.g. "Vaal Aspect" base-type jewels like Cooperation - see
 * lib/category-reliability.ts's correctedItemType) need no special-casing to exclude: they aren't
 * stackable/exchange-tradeable at all, so they never appear in GGG's exchange data to begin with.
 */
import "server-only";
import { goldCostFor, type GoldCost } from "./faustus-gold";

const EXCHANGE_URL = "https://web.poecdn.com/api/currency-exchange";
const CACHE_TTL_MS = 20 * 60 * 1000; // same cadence as poe-ninja.ts's other overview caches
const USER_AGENT = "poe-flipper/0.1.0 (personal, non-commercial; unaffiliated with GGG)";
const CHAOS_ID = "Metadata/Items/Currency/CurrencyRerollRare";
const DIVINE_ID = "Metadata/Items/Currency/CurrencyModValues";

// Generated by scripts/generate-faustus-mapping.ts from RePoE + a live GGG exchange snapshot -
// do not hand-edit; re-run the generator instead.
export const FAUSTUS_NAME_TO_ID: Readonly<Record<string, string>> = {
  "A Fate Worse Than Death": "Metadata/Items/DivinationCards/DivinationCardAFateWorseThanDeath",
  "A Note in the Wind": "Metadata/Items/DivinationCards/DivinationCardANoteInTheWind",
  "A Stone Perfected": "Metadata/Items/DivinationCards/DivinationCardAStonePerfected",
  "Aberrant Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingChaos",
  "Abrasive Catalyst": "Metadata/Items/Currency/CurrencyJewelleryQualityAttack",
  "Abyss Scarab": "Metadata/Items/Scarabs/ScarabAbyssNew1",
  "Abyss Scarab of Crystals": "Metadata/Items/Scarabs/ScarabAbyssNew4",
  "Abyss Scarab of Descending": "Metadata/Items/Scarabs/ScarabAbyssNew3",
  "Abyss Scarab of Multitudes": "Metadata/Items/Scarabs/ScarabAbyssNew2",
  "Abyss Scarab of the Consort": "Metadata/Items/Scarabs/ScarabAbyssNew5",
  "Accelerating Catalyst": "Metadata/Items/Currency/CurrencyJewelleryQualitySpeed",
  "Aetheric Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingCasterMods",
  "Al-Hezmin's Crest": "Metadata/Items/MapFragments/CurrencySirusFragment1",
  "Alchemy Shard": "Metadata/Items/Currency/CurrencyUpgradeToRareShard",
  "Allflame Ember of Flesh": "Metadata/Items/MapFragments/MeatSackAllflamePack",
  "Allflame Ember of Kulemak": "Metadata/Items/MapFragments/BetrayalAllflamePack",
  "Allflame Ember of Propagation": "Metadata/Items/MapFragments/PropagationAllflamePack",
  "Allflame Ember of Resplendence": "Metadata/Items/MapFragments/ResplendenceAllflamePack",
  "Allflame Ember of the Ethereal": "Metadata/Items/MapFragments/CleansedAllflamePack",
  "Allflame Ember of the Gilded": "Metadata/Items/MapFragments/GoldAllflamePack",
  "Allflame Ember of the Wildwood": "Metadata/Items/MapFragments/WildwoodAllflamePack",
  "Allflame Ember of Toads": "Metadata/Items/MapFragments/ToadAllflamePack",
  "Amber Oil": "Metadata/Items/Currency/Mushrune3",
  "Ambush Scarab": "Metadata/Items/Scarabs/ScarabStrongboxNew1",
  "Ambush Scarab of Containment": "Metadata/Items/Scarabs/ScarabStrongboxNew4",
  "Ambush Scarab of Discernment": "Metadata/Items/Scarabs/ScarabStrongboxNew5",
  "Ambush Scarab of Hidden Compartments": "Metadata/Items/Scarabs/ScarabStrongboxNew2",
  "Ambush Scarab of Potency": "Metadata/Items/Scarabs/ScarabStrongboxNew3",
  "An Audience With The King": "Metadata/Items/MapFragments/RitualBossFragment",
  "Anarchy Scarab": "Metadata/Items/Scarabs/ScarabAnarchy1",
  "Anarchy Scarab of Gigantification": "Metadata/Items/Scarabs/ScarabAnarchy2",
  "Anarchy Scarab of Partnership": "Metadata/Items/Scarabs/ScarabAnarchy3",
  "Anarchy Scarab of the Exceptional": "Metadata/Items/Scarabs/ScarabAnarchy4",
  "Anarchy's Price": "Metadata/Items/DivinationCards/DivinationCardAnarchysPrice",
  "Ancient Orb": "Metadata/Items/Currency/CurrencyRerollUnique",
  "Apocalypse": "Metadata/Items/DivinationCards/DivinationCardApocalypse",
  "Armourer's Scrap": "Metadata/Items/Currency/CurrencyArmourQuality",
  "Armoursmith's Delirium Orb": "Metadata/Items/Currency/CurrencyAfflictionOrbArmour",
  "Arrogance of the Vaal": "Metadata/Items/DivinationCards/DivinationCardArroganceOfTheVaal",
  "Atziri's Arsenal": "Metadata/Items/DivinationCards/DivinationCardAtzirisArsenal",
  "Avian Pursuit": "Metadata/Items/DivinationCards/DivinationCardAvianPursuit",
  "Awakener's Orb": "Metadata/Items/AtlasExiles/ApplyInfluence",
  "Awakening Fragment": "Metadata/Items/MapFragments/CurrencyUberBossKeySirus",
  "Azure Oil": "Metadata/Items/Currency/Mushrune6",
  "Azyran's Reward": "Metadata/Items/DivinationCards/DivinationCardAzyransReward",
  "Baited Expectations": "Metadata/Items/DivinationCards/DivinationCardBaitedExpectations",
  "Baran's Crest": "Metadata/Items/MapFragments/CurrencySirusFragment2",
  "Bestiary Scarab": "Metadata/Items/Scarabs/ScarabBeastsNew1",
  "Bestiary Scarab of Duplicating": "Metadata/Items/Scarabs/ScarabBeastsNew3",
  "Bestiary Scarab of the Herd": "Metadata/Items/Scarabs/ScarabBeastsNew2",
  "Betrayal Scarab": "Metadata/Items/Scarabs/ScarabBetrayal1",
  "Betrayal Scarab of Reinforcements": "Metadata/Items/Scarabs/ScarabBetrayal3",
  "Betrayal Scarab of the Allflame": "Metadata/Items/Scarabs/ScarabBetrayal2",
  "Betrayal Scarab of Unbreaking": "Metadata/Items/Scarabs/ScarabBetrayal4",
  "Beyond Scarab": "Metadata/Items/Scarabs/ScarabBeyond1",
  "Beyond Scarab of Haemophilia": "Metadata/Items/Scarabs/ScarabBeyond3",
  "Beyond Scarab of Resurgence": "Metadata/Items/Scarabs/ScarabBeyond4",
  "Beyond Scarab of the Invasion": "Metadata/Items/Scarabs/ScarabBeyond5",
  "Black Oil": "Metadata/Items/Currency/Mushrune9",
  "Blacksmith's Delirium Orb": "Metadata/Items/Currency/CurrencyAfflictionOrbWeapons",
  "Blacksmith's Whetstone": "Metadata/Items/Currency/CurrencyWeaponQuality",
  "Blazing Fragment": "Metadata/Items/MapFragments/CurrencyUberBossKeyExarch",
  "Blessed Orb": "Metadata/Items/Currency/CurrencyRerollImplicit",
  "Blight Scarab": "Metadata/Items/Scarabs/ScarabBlightNew1",
  "Blight Scarab of Blooming": "Metadata/Items/Scarabs/ScarabBlightNew4",
  "Blight Scarab of Invigoration": "Metadata/Items/Scarabs/ScarabBlightNew5",
  "Blight Scarab of the Blightheart": "Metadata/Items/Scarabs/ScarabBlightNew3",
  "Blighted Delirium Orb": "Metadata/Items/Currency/CurrencyAfflictionOrbBlight",
  "Blind Venture": "Metadata/Items/DivinationCards/DivinationCardBlindVenture",
  "Bloodstained Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingVaal",
  "Bound by Flame": "Metadata/Items/DivinationCards/DivinationCardBoundByFlame",
  "Bound Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingMinionsAuras",
  "Breach Scarab of Instability": "Metadata/Items/Scarabs/ScarabBreachNew3",
  "Breach Scarab of Resonant Cascade": "Metadata/Items/Scarabs/ScarabBreachNew6",
  "Breach Scarab of the Hive": "Metadata/Items/Scarabs/ScarabBreachNew1",
  "Breach Scarab of the Incensed Swarm": "Metadata/Items/Scarabs/ScarabBreachNew5",
  "Breach Scarab of the Marshal": "Metadata/Items/Scarabs/ScarabBreachNew4",
  "Brinehook's Ducat": "Metadata/Items/Deepwater/DeepwaterPantheon",
  "Brother's Gift": "Metadata/Items/DivinationCards/DivinationCardBrothersGift",
  "Brush, Paint and Palette": "Metadata/Items/DivinationCards/DivinationCardBrushPaintAndPalette",
  "Burial Medallion": "Metadata/Items/Currency/CurrencyRefreshSaga",
  "Cameria's Cut": "Metadata/Items/DivinationCards/DivinationCardCameriasCut",
  "Cartographer's Delirium Orb": "Metadata/Items/Currency/CurrencyAfflictionOrbMaps",
  "Cartography Scarab of Corruption": "Metadata/Items/Scarabs/ScarabMapsNew4",
  "Cartography Scarab of Escalation": "Metadata/Items/Scarabs/ScarabMapsNew1",
  "Cartography Scarab of Risk": "Metadata/Items/Scarabs/ScarabMapsNew2",
  "Cartography Scarab of the Multitude": "Metadata/Items/Scarabs/ScarabMapsNew5",
  "Chaos Orb": "Metadata/Items/Currency/CurrencyRerollRare",
  "Chaotic Astrolabe": "Metadata/Items/Currency/AstrolabeUltimatum",
  "Chaotic Disposition": "Metadata/Items/DivinationCards/DivinationCardChaoticDisposition",
  "Chromatic Orb": "Metadata/Items/Currency/CurrencyRerollSocketColours",
  "Clear Oil": "Metadata/Items/Currency/Mushrune1",
  "Corroded Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingBleedPoison",
  "Cosmic Fragment": "Metadata/Items/MapFragments/CurrencyUberBossKeyShaper",
  "Crescent Splinter": "Metadata/Items/MapFragments/CurrencyMavenKeyFragment",
  "Crimson Oil": "Metadata/Items/Currency/Mushrune8",
  "Crusader's Exalted Orb": "Metadata/Items/AtlasExiles/AddModToRareCrusader",
  "Crystallised Rancour": "Metadata/Items/Currency/HarvestSeedFaridun",
  "Cyaxan's Ducat": "Metadata/Items/Deepwater/DeepwaterMercenaryCurrency",
  "Damnation": "Metadata/Items/DivinationCards/DivinationCardDamnation",
  "Darker Half": "Metadata/Items/DivinationCards/DivinationCardDarkerHalf",
  "Dead Man's Sulphur": "Metadata/Items/Currency/CurrencyDeepwater",
  "Deafening Essence of Anger": "Metadata/Items/Currency/CurrencyEssenceAnger6",
  "Deafening Essence of Anguish": "Metadata/Items/Currency/CurrencyEssenceAnguish4",
  "Deafening Essence of Contempt": "Metadata/Items/Currency/CurrencyEssenceContempt7",
  "Deafening Essence of Doubt": "Metadata/Items/Currency/CurrencyEssenceDoubt5",
  "Deafening Essence of Dread": "Metadata/Items/Currency/CurrencyEssenceDread3",
  "Deafening Essence of Envy": "Metadata/Items/Currency/CurrencyEssenceEnvy3",
  "Deafening Essence of Fear": "Metadata/Items/Currency/CurrencyEssenceFear6",
  "Deafening Essence of Greed": "Metadata/Items/Currency/CurrencyEssenceGreed7",
  "Deafening Essence of Hatred": "Metadata/Items/Currency/CurrencyEssenceHatred7",
  "Deafening Essence of Loathing": "Metadata/Items/Currency/CurrencyEssenceLoathing4",
  "Deafening Essence of Misery": "Metadata/Items/Currency/CurrencyEssenceMisery3",
  "Deafening Essence of Rage": "Metadata/Items/Currency/CurrencyEssenceRage5",
  "Deafening Essence of Scorn": "Metadata/Items/Currency/CurrencyEssenceScorn3",
  "Deafening Essence of Sorrow": "Metadata/Items/Currency/CurrencyEssenceSorrow6",
  "Deafening Essence of Spite": "Metadata/Items/Currency/CurrencyEssenceSpite4",
  "Deafening Essence of Suffering": "Metadata/Items/Currency/CurrencyEssenceSuffering5",
  "Deafening Essence of Torment": "Metadata/Items/Currency/CurrencyEssenceTorment6",
  "Deafening Essence of Woe": "Metadata/Items/Currency/CurrencyEssenceWoe7",
  "Deafening Essence of Wrath": "Metadata/Items/Currency/CurrencyEssenceWrath5",
  "Deafening Essence of Zeal": "Metadata/Items/Currency/CurrencyEssenceZeal4",
  "Death": "Metadata/Items/DivinationCards/DivinationCardDeath",
  "Decaying Fragment": "Metadata/Items/MapFragments/CurrencyUberBossKeyUberElder",
  "Deceptive Astrolabe": "Metadata/Items/Currency/AstrolabeDelirium",
  "Dedication to the Goddess": "Metadata/Items/MapFragments/CurrencyOfferingToTheGoddessDedication",
  "Deft Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingEnchant",
  "Delirium Orb": "Metadata/Items/Currency/CurrencyAfflictionOrbGeneric",
  "Delirium Scarab": "Metadata/Items/Scarabs/ScarabDelirium1",
  "Delirium Scarab of Delusions": "Metadata/Items/Scarabs/ScarabDelirium5",
  "Delirium Scarab of Mania": "Metadata/Items/Scarabs/ScarabDelirium2",
  "Delirium Scarab of Neuroses": "Metadata/Items/Scarabs/ScarabDelirium4",
  "Delirium Scarab of Paranoia": "Metadata/Items/Scarabs/ScarabDelirium3",
  "Dementophobia": "Metadata/Items/DivinationCards/DivinationCardDementophobia",
  "Dense Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingDefences",
  "Desecrated Virtue": "Metadata/Items/DivinationCards/DivinationCardDesecratedVirtue",
  "Desperate Crusade": "Metadata/Items/DivinationCards/DivinationCardDesperateCrusade",
  "Destined to Crumble": "Metadata/Items/DivinationCards/DivinationCardDestinedToCrumble",
  "Devouring Fragment": "Metadata/Items/MapFragments/CurrencyUberBossKeyEater",
  "Divination Scarab of Pilfering": "Metadata/Items/Scarabs/ScarabDivinationCardsNew3",
  "Divination Scarab of Plenty": "Metadata/Items/Scarabs/ScarabDivinationCardsNew2",
  "Divination Scarab of The Cloister": "Metadata/Items/Scarabs/ScarabDivinationCardsNew1",
  "Divine Beauty": "Metadata/Items/DivinationCards/DivinationCardDivineBeauty",
  "Divine Orb": "Metadata/Items/Currency/CurrencyModValues",
  "Divine Vessel": "Metadata/Items/MapFragments/CurrencyFragmentPantheonFlask",
  "Diviner's Delirium Orb": "Metadata/Items/Currency/CurrencyAfflictionOrbDivinationCards",
  "Domination Scarab": "Metadata/Items/Scarabs/ScarabDomination1",
  "Domination Scarab of Apparitions": "Metadata/Items/Scarabs/ScarabDomination2",
  "Domination Scarab of Evolution": "Metadata/Items/Scarabs/ScarabDomination3",
  "Domination Scarab of Terrors": "Metadata/Items/Scarabs/ScarabDomination4",
  "Doryani's Epiphany": "Metadata/Items/DivinationCards/DivinationCardDoryanisEpiphany",
  "Drox's Crest": "Metadata/Items/MapFragments/CurrencySirusFragment3",
  "Echo of Loneliness": "Metadata/Items/MapFragments/AtlasMemory/CurrencyIgnoranceKey",
  "Echo of Reverence": "Metadata/Items/MapFragments/AtlasMemory/CurrencyBenevolenceKey",
  "Echo of Trauma": "Metadata/Items/MapFragments/AtlasMemory/CurrencyFearKey",
  "Echoes of Love": "Metadata/Items/DivinationCards/DivinationCardEchoesOfLove",
  "Elder's Exalted Orb": "Metadata/Items/Currency/CurrencyAddModToRareElder",
  "Eldritch Chaos Orb": "Metadata/Items/Currency/CurrencyEldritchRerollRare",
  "Eldritch Exalted Orb": "Metadata/Items/Currency/CurrencyEldritchAddModToRare",
  "Eldritch Orb of Annulment": "Metadata/Items/Currency/CurrencyEldritchRemoveMod",
  "Emperor of Purity": "Metadata/Items/DivinationCards/DivinationCardEmperorOfPurity",
  "Enkindling Orb": "Metadata/Items/Currency/CurrencyEnkindlingOrb",
  "Essence of Delirium": "Metadata/Items/Currency/CurrencyEssenceDelirium1",
  "Essence of Horror": "Metadata/Items/Currency/CurrencyEssenceHorror1",
  "Essence of Hysteria": "Metadata/Items/Currency/CurrencyEssenceHysteria1",
  "Essence of Insanity": "Metadata/Items/Currency/CurrencyEssenceInsanity1",
  "Essence Scarab": "Metadata/Items/Scarabs/ScarabEssence1",
  "Essence Scarab of Adaptation": "Metadata/Items/Scarabs/ScarabEssence5",
  "Essence Scarab of Ascent": "Metadata/Items/Scarabs/ScarabEssence2",
  "Essence Scarab of Calcification": "Metadata/Items/Scarabs/ScarabEssence4",
  "Essence Scarab of Stability": "Metadata/Items/Scarabs/ScarabEssence3",
  "Exalted Orb": "Metadata/Items/Currency/CurrencyAddModToRare",
  "Exceptional Eldritch Ember": "Metadata/Items/Currency/CurrencyEldritchEmber4",
  "Exceptional Eldritch Ichor": "Metadata/Items/Currency/CurrencyEldritchIchor4",
  "Exotic Coinage": "Metadata/Items/Currency/CurrencyRefreshBarter",
  "Expedition Scarab": "Metadata/Items/Scarabs/ScarabExpedition1",
  "Expedition Scarab of Archaeology": "Metadata/Items/Scarabs/ScarabExpedition5",
  "Expedition Scarab of Infusion": "Metadata/Items/Scarabs/ScarabExpedition4",
  "Expedition Scarab of Runefinding": "Metadata/Items/Scarabs/ScarabExpedition2",
  "Expedition Scarab of Verisium Powder": "Metadata/Items/Scarabs/ScarabExpedition3",
  "Faceted Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingGemLevel",
  "Fateful Meeting": "Metadata/Items/DivinationCards/DivinationCardFatefulMeeting",
  "Father's Love": "Metadata/Items/DivinationCards/DivinationCardFathersLove",
  "Fertile Catalyst": "Metadata/Items/Currency/CurrencyJewelleryQualityResource",
  "Fine Delirium Orb": "Metadata/Items/Currency/CurrencyAfflictionOrbCurrency",
  "Fire Of Unknown Origin": "Metadata/Items/DivinationCards/DivinationCardFireOfUnknownOrigin",
  "Flesh of Xesht": "Metadata/Items/Currency/CurrencyBreachUpgradeUniqueGeneral",
  "Foulborn Exalted Orb": "Metadata/Items/Currency/CurrencyMutatedAddModToRare",
  "Foulborn Orb of Augmentation": "Metadata/Items/Currency/CurrencyMutatedAddModToMagic",
  "Foulborn Regal Orb": "Metadata/Items/Currency/CurrencyMutatedUpgradeMagicToRare",
  "Fractured Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingMirror",
  "Fracturing Orb": "Metadata/Items/Currency/CurrencyFractureRare",
  "Fracturing Shard": "Metadata/Items/Currency/CurrencyFractureRareShard",
  "Fragment of Constriction": "Metadata/Items/MapFragments/CurrencyElderFragment3",
  "Fragment of Emptiness": "Metadata/Items/MapFragments/CurrencyUberElderFragment2",
  "Fragment of Enslavement": "Metadata/Items/MapFragments/CurrencyElderFragment1",
  "Fragment of Eradication": "Metadata/Items/MapFragments/CurrencyElderFragment2",
  "Fragment of Knowledge": "Metadata/Items/MapFragments/CurrencyUberElderFragment4",
  "Fragment of Purification": "Metadata/Items/MapFragments/CurrencyElderFragment4",
  "Fragment of Shape": "Metadata/Items/MapFragments/CurrencyUberElderFragment3",
  "Fragment of Terror": "Metadata/Items/MapFragments/CurrencyUberElderFragment1",
  "Fragment of the Chimera": "Metadata/Items/MapFragments/CurrencyShaperFragment3",
  "Fragment of the Hydra": "Metadata/Items/MapFragments/CurrencyShaperFragment4",
  "Fragment of the Minotaur": "Metadata/Items/MapFragments/CurrencyShaperFragment2",
  "Fragment of the Phoenix": "Metadata/Items/MapFragments/CurrencyShaperFragment1",
  "Fragmented Delirium Orb": "Metadata/Items/Currency/CurrencyAfflictionOrbFragments",
  "Frigid Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingCold",
  "Fruiting Astrolabe": "Metadata/Items/Currency/AstrolabeHarvest",
  "Fundamental Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingSockets",
  "Fungal Astrolabe": "Metadata/Items/Currency/AstrolabeBlight",
  "Gemcutter's Mercy": "Metadata/Items/DivinationCards/DivinationCardGemcuttersMercy",
  "Gemcutter's Prism": "Metadata/Items/Currency/CurrencyGemQuality",
  "Gift to the Goddess": "Metadata/Items/MapFragments/CurrencyOfferingToTheGoddessGift",
  "Gilded Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingSellPrice",
  "Glassblower's Bauble": "Metadata/Items/Currency/CurrencyFlaskQuality",
  "Glyphic Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingCorruptEssence",
  "Golden Oil": "Metadata/Items/Currency/Mushrune12",
  "Grand Eldritch Ember": "Metadata/Items/Currency/CurrencyEldritchEmber3",
  "Grand Eldritch Ichor": "Metadata/Items/Currency/CurrencyEldritchIchor3",
  "Grasping Astrolabe": "Metadata/Items/Currency/AstrolabeBreach",
  "Greater Eldritch Ember": "Metadata/Items/Currency/CurrencyEldritchEmber2",
  "Greater Eldritch Ichor": "Metadata/Items/Currency/CurrencyEldritchIchor2",
  "Harvest Scarab": "Metadata/Items/Scarabs/ScarabHarvest1",
  "Harvest Scarab of Cornucopia": "Metadata/Items/Scarabs/ScarabHarvest3",
  "Harvest Scarab of Doubling": "Metadata/Items/Scarabs/ScarabHarvest2",
  "Haunting Shadows": "Metadata/Items/DivinationCards/DivinationCardHauntingShadows",
  "Hinekora's Lock": "Metadata/Items/Currency/CurrencyHinekorasLock",
  "History": "Metadata/Items/DivinationCards/DivinationCardHistory",
  "Hivebrain Gland": "Metadata/Items/MapFragments/CurrencyBrequelBossKey",
  "Hollow Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingAbyss",
  "Home": "Metadata/Items/DivinationCards/DivinationCardHome",
  "Horned Scarab of Awakening": "Metadata/Items/Scarabs/ScarabUber4",
  "Horned Scarab of Bloodlines": "Metadata/Items/Scarabs/ScarabUber1",
  "Horned Scarab of Glittering": "Metadata/Items/Scarabs/ScarabUber6",
  "Horned Scarab of Nemeses": "Metadata/Items/Scarabs/ScarabUber2",
  "Horned Scarab of Pandemonium": "Metadata/Items/Scarabs/ScarabUber7",
  "Horned Scarab of Preservation": "Metadata/Items/Scarabs/ScarabUber3",
  "Horned Scarab of Tradition": "Metadata/Items/Scarabs/ScarabUber5",
  "House of Mirrors": "Metadata/Items/DivinationCards/DivinationCardHouseOfMirrors",
  "Hunter's Exalted Orb": "Metadata/Items/AtlasExiles/AddModToRareHunter",
  "I See Brothers": "Metadata/Items/DivinationCards/DivinationCardISeeBrothers",
  "Imbued Catalyst": "Metadata/Items/Currency/CurrencyJewelleryQualityCaster",
  "Imperial Enshrouding Crystal": "Metadata/Items/Currency/LegionCocoonBoots",
  "Incursion Scarab": "Metadata/Items/Scarabs/ScarabIncursion1",
  "Incursion Scarab of Champions": "Metadata/Items/Scarabs/ScarabIncursion3",
  "Incursion Scarab of Invasion": "Metadata/Items/Scarabs/ScarabIncursion2",
  "Incursion Scarab of Timelines": "Metadata/Items/Scarabs/ScarabIncursion4",
  "Indigo Oil": "Metadata/Items/Currency/Mushrune6b",
  "Influencing Scarab of Hordes": "Metadata/Items/Scarabs/ScarabInfluenceNew3",
  "Influencing Scarab of Interference": "Metadata/Items/Scarabs/ScarabInfluenceNew4",
  "Influencing Scarab of the Elder": "Metadata/Items/Scarabs/ScarabInfluenceNew2",
  "Influencing Scarab of the Shaper": "Metadata/Items/Scarabs/ScarabInfluenceNew1",
  "Instilling Orb": "Metadata/Items/Currency/CurrencyInstillingOrb",
  "Intrinsic Catalyst": "Metadata/Items/Currency/CurrencyJewelleryQualityAttribute",
  "Jagged Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingPhysical",
  "Jeweller's Delirium Orb": "Metadata/Items/Currency/CurrencyAfflictionOrbTrinkets",
  "Jeweller's Orb": "Metadata/Items/Currency/CurrencyRerollSocketNumbers",
  "Journey Tattoo of the Soul": "Metadata/Items/Currency/AncestralTattooSpecialUnique5",
  "Kalguuran Scarab": "Metadata/Items/Scarabs/ScarabSettlers1",
  "Kalguuran Scarab of Enriching": "Metadata/Items/Scarabs/ScarabSettlers4",
  "Kalguuran Scarab of Guarded Riches": "Metadata/Items/Scarabs/ScarabSettlers2",
  "Kalguuran Scarab of Refinement": "Metadata/Items/Scarabs/ScarabSettlers3",
  "Karui Enshrouding Crystal": "Metadata/Items/Currency/LegionCocoonGloves",
  "Katakohi's Ducat": "Metadata/Items/Deepwater/DeepwaterTatttoo",
  "Kishara's Ducat": "Metadata/Items/Deepwater/DeepwaterItemSplit",
  "Lachrymal Necrosis": "Metadata/Items/DivinationCards/DivinationCardLachrymalNecrosis",
  "Last Hope": "Metadata/Items/DivinationCards/DivinationCardLastHope",
  "Legion Scarab": "Metadata/Items/Scarabs/ScarabLegionNew1",
  "Legion Scarab of Eternal Conflict": "Metadata/Items/Scarabs/ScarabLegionNew5",
  "Legion Scarab of Officers": "Metadata/Items/Scarabs/ScarabLegionNew2",
  "Legion Scarab of Treasures": "Metadata/Items/Scarabs/ScarabLegionNew3",
  "Lesser Eldritch Ember": "Metadata/Items/Currency/CurrencyEldritchEmber1",
  "Lesser Eldritch Ichor": "Metadata/Items/Currency/CurrencyEldritchIchor1",
  "Light and Truth": "Metadata/Items/DivinationCards/DivinationCardLightAndTruth",
  "Lightless Astrolabe": "Metadata/Items/Currency/AstrolabeAbyss",
  "Lingering Remnants": "Metadata/Items/DivinationCards/DivinationCardLingeringRemnants",
  "Lonely Fragment": "Metadata/Items/MapFragments/CurrencyUberBossKeyIgnorance",
  "Love Through Ice": "Metadata/Items/DivinationCards/DivinationCardLoveThroughIce",
  "Lucent Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingMana",
  "Luminous Trove": "Metadata/Items/DivinationCards/DivinationCardLuminousTrove",
  "Maraketh Enshrouding Crystal": "Metadata/Items/Currency/LegionCocoonBodyArmour",
  "Matryoshka": "Metadata/Items/DivinationCards/DivinationCardMatryoshka",
  "Maven's Chisel of Avarice": "Metadata/Items/Currency/CurrencyMapQualityCurrency",
  "Maven's Chisel of Divination": "Metadata/Items/Currency/CurrencyMapQualityDivinationCards",
  "Maven's Chisel of Procurement": "Metadata/Items/Currency/CurrencyMapQualityRarity",
  "Maven's Chisel of Proliferation": "Metadata/Items/Currency/CurrencyMapQualityPackSize",
  "Maven's Chisel of Scarabs": "Metadata/Items/Currency/CurrencyMapQualityScarabs",
  "Mawr Blaidd": "Metadata/Items/DivinationCards/DivinationCardMawrBlaidd",
  "Memory of Loneliness": "Metadata/Items/Currency/IgnoranceMemoryThread",
  "Memory of Reverence": "Metadata/Items/Currency/BenevolenceMemoryThread",
  "Memory of Trauma": "Metadata/Items/Currency/FearMemoryThread",
  "Merrick's Ducat": "Metadata/Items/Deepwater/DeepwaterAbyssCurrency",
  "Message in a Bottle": "Metadata/Items/Deepwater/DeepwaterBottledItem",
  "Metallic Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingLightning",
  "Might is Right": "Metadata/Items/DivinationCards/DivinationCardMightIsRight",
  "Mirror of Kalandra": "Metadata/Items/Currency/CurrencyDuplicate",
  "Mirror Shard": "Metadata/Items/Currency/CurrencyDuplicateShard",
  "Monochrome": "Metadata/Items/DivinationCards/DivinationCardMonochrome",
  "More is Never Enough": "Metadata/Items/DivinationCards/DivinationCardMoreIsNeverEnough",
  "Mortal Grief": "Metadata/Items/MapFragments/CurrencyVaalFragment2_4",
  "Mortal Hope": "Metadata/Items/MapFragments/CurrencyVaalFragment2_2",
  "Mortal Ignorance": "Metadata/Items/MapFragments/CurrencyVaalFragment2_3",
  "Mortal Rage": "Metadata/Items/MapFragments/CurrencyVaalFragment2_1",
  "Muttering Essence of Fear": "Metadata/Items/Currency/CurrencyEssenceFear1",
  "Muttering Essence of Woe": "Metadata/Items/Currency/CurrencyEssenceWoe2",
  "Nameless Astrolabe": "Metadata/Items/Currency/AstrolabeRitual",
  "No Traces": "Metadata/Items/DivinationCards/DivinationCardNoTraces",
  "Noxious Catalyst": "Metadata/Items/Currency/CurrencyJewelleryQualityPhysicalChaos",
  "Offering to the Goddess": "Metadata/Items/MapFragments/CurrencyOfferingToTheGoddess",
  "Omen of Amelioration": "Metadata/Items/Currency/AncestralOmenOnDeathPreventExpLoss",
  "Omen of Brilliance": "Metadata/Items/Currency/AncestralOmenOnLevelingUpGainExperienceBuff",
  "Omen of Connections": "Metadata/Items/Currency/AncestralOmenOnFusingMakeFullLinks",
  "Omen of Death-dancing": "Metadata/Items/Currency/AncestralOmenOnCriticalLifeAvoidDamage",
  "Omen of Fortune": "Metadata/Items/Currency/AncestralOmenOnChanceMakeUnique",
  "Omen of Return": "Metadata/Items/Currency/AncestralOmenOnDeathCreatePortal",
  "Omen of the Jeweller": "Metadata/Items/Currency/AncestralOmenOnJewellersMakeFullSockets",
  "Omen of Trichromatism": "Metadata/Items/Currency/AncestralOmenOnChromaticAddWhiteSockets",
  "Opalescent Oil": "Metadata/Items/Currency/Mushrune10",
  "Opulent Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingQuality",
  "Orb of Alchemy": "Metadata/Items/Currency/CurrencyUpgradeToRare",
  "Orb of Alteration": "Metadata/Items/Currency/CurrencyRerollMagic",
  "Orb of Annulment": "Metadata/Items/Currency/CurrencyRemoveMod",
  "Orb of Augmentation": "Metadata/Items/Currency/CurrencyAddModToMagic",
  "Orb of Chance": "Metadata/Items/Currency/CurrencyUpgradeRandomly",
  "Orb of Conflict": "Metadata/Items/Currency/CurrencyConflictOrb",
  "Orb of Dominance": "Metadata/Items/Currency/CurrencyUpgradeInfluenceMod",
  "Orb of Fusing": "Metadata/Items/Currency/CurrencyRerollSocketLinks",
  "Orb of Intention": "Metadata/Items/Currency/CurrencyMoreZanaInfluencedItems",
  "Orb of Regret": "Metadata/Items/Currency/CurrencyPassiveRefund",
  "Orb of Remembrance": "Metadata/Items/Currency/CurrencyAddZanaInfluence",
  "Orb of Scouring": "Metadata/Items/Currency/CurrencyConvertToNormal",
  "Orb of Transmutation": "Metadata/Items/Currency/CurrencyUpgradeToMagic",
  "Orb of Unmaking": "Metadata/Items/Currency/CurrencyAtlasPassiveRefund",
  "Orb of Unravelling": "Metadata/Items/Currency/CurrencyRemoveZanaInfluence",
  "Outfoxed": "Metadata/Items/DivinationCards/DivinationCardOutfoxed",
  "Peaceful Moments": "Metadata/Items/DivinationCards/DivinationCardPeacefulMoments",
  "Portal Scroll": "Metadata/Items/Currency/CurrencyPortal",
  "Pride Before the Fall": "Metadata/Items/DivinationCards/DivinationCardPrideBeforeTheFall",
  "Primal Crystallised Lifeforce": "Metadata/Items/Currency/HarvestSeedBlue",
  "Prismatic Catalyst": "Metadata/Items/Currency/CurrencyJewelleryQualityResistance",
  "Prismatic Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingElemental",
  "Prismatic Oil": "Metadata/Items/Currency/MushruneUber",
  "Pristine Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingLife",
  "Reality Fragment": "Metadata/Items/MapFragments/CurrencyUberBossKeyMaven",
  "Rebirth and Renewal": "Metadata/Items/DivinationCards/DivinationCardRebirthAndRenewal",
  "Redeemer's Exalted Orb": "Metadata/Items/AtlasExiles/AddModToRareRedeemer",
  "Reflecting Mist": "Metadata/Items/Currency/ReflectiveMist",
  "Reflection of the Heart": "Metadata/Items/DivinationCards/DivinationCardTheReflectionoftheHeart",
  "Reflective Oil": "Metadata/Items/Currency/MushruneMirror",
  "Regal Orb": "Metadata/Items/Currency/CurrencyUpgradeMagicToRare",
  "Reverent Fragment": "Metadata/Items/MapFragments/CurrencyUberBossKeyBenevolence",
  "Ritual Scarab of Abundance": "Metadata/Items/Scarabs/ScarabRitual3",
  "Ritual Scarab of Corpses": "Metadata/Items/Scarabs/ScarabRitual4",
  "Ritual Scarab of Selectiveness": "Metadata/Items/Scarabs/ScarabRitual1",
  "Ritual Scarab of Wisps": "Metadata/Items/Scarabs/ScarabRitual2",
  "Ritual Splinter": "Metadata/Items/Currency/CurrencyRitualSplinter",
  "Ritual Vessel": "Metadata/Items/Currency/CurrencyRitualStone",
  "Rogue's Marker": "Metadata/Items/Heist/HeistCoin",
  "Rotmother's Ducat": "Metadata/Items/Deepwater/DeepwaterSaboteur",
  "Runegraft of Bellows": "Metadata/Items/Currency/RunegraftWarcrySpeed",
  "Runegraft of Blasphemy": "Metadata/Items/Currency/RunegraftRandomCurse",
  "Runegraft of Connection": "Metadata/Items/Currency/RunegraftConnection",
  "Runegraft of Consecration": "Metadata/Items/Currency/RunegraftConsecratedGround",
  "Runegraft of Gemcraft": "Metadata/Items/Currency/RunegraftSupportLevels",
  "Runegraft of Loyalty": "Metadata/Items/Currency/RunegraftAilmentRedirect",
  "Runegraft of Quaffing": "Metadata/Items/Currency/RunegraftLifeFromManaFlasks",
  "Runegraft of Rallying": "Metadata/Items/Currency/RunegraftFortificationBanner",
  "Runegraft of Refraction": "Metadata/Items/Currency/RunegraftChainMana",
  "Runegraft of Restitching": "Metadata/Items/Currency/RunegraftCritRecoup",
  "Runegraft of Resurgence": "Metadata/Items/Currency/RunegraftResurgence",
  "Runegraft of Stability": "Metadata/Items/Currency/RunegraftUnexciting",
  "Runegraft of Suffering": "Metadata/Items/Currency/RunegraftSuffering",
  "Runegraft of the Agile": "Metadata/Items/Currency/RunegraftElusive",
  "Runegraft of the Angler": "Metadata/Items/Currency/RunegraftFishing",
  "Runegraft of the Bound": "Metadata/Items/Currency/RunegraftBootsGloves",
  "Runegraft of the Combatant": "Metadata/Items/Currency/RunegraftMatchedAttackDamage",
  "Runegraft of the Fortress": "Metadata/Items/Currency/RunegraftAttributeGlobalDefences",
  "Runegraft of the Imbued": "Metadata/Items/Currency/RunegraftTinctures",
  "Runegraft of the Jeweller": "Metadata/Items/Currency/RunegraftDamagePerSocket",
  "Runegraft of the Novamark": "Metadata/Items/Currency/RunegraftNovaMarkedTarget",
  "Runegraft of the River": "Metadata/Items/Currency/RunegraftLowLifeRestore",
  "Runegraft of the Sinistral": "Metadata/Items/Currency/RunegraftFlatOffhandAttackTime",
  "Runegraft of the Soulwick": "Metadata/Items/Currency/RunegraftSouls",
  "Runegraft of the Spellbound": "Metadata/Items/Currency/RunegraftSpellbound",
  "Runegraft of the Warp": "Metadata/Items/Currency/RunegraftBuffScaling",
  "Runegraft of the Witchmark": "Metadata/Items/Currency/RunegraftSpellLifeCost",
  "Runegraft of Time": "Metadata/Items/Currency/RunegraftCooldownRefresh",
  "Runegraft of Treachery": "Metadata/Items/Currency/RunegraftTreacherousAuras",
  "Runic Astrolabe": "Metadata/Items/Currency/AstrolabeExpedition",
  "Sacred Blossom": "Metadata/Items/MapFragments/CurrencyHarvestBossKey",
  "Sacred Crystallised Lifeforce": "Metadata/Items/Currency/HarvestSeedBoss",
  "Sacred Orb": "Metadata/Items/Currency/CurrencyRerollDefences",
  "Sacrifice at Dawn": "Metadata/Items/MapFragments/CurrencyVaalFragment1_2",
  "Sacrifice at Dusk": "Metadata/Items/MapFragments/CurrencyVaalFragment1_4",
  "Sacrifice at Midnight": "Metadata/Items/MapFragments/CurrencyVaalFragment1_1",
  "Sacrifice at Noon": "Metadata/Items/MapFragments/CurrencyVaalFragment1_3",
  "Sambodhi's Vow": "Metadata/Items/DivinationCards/DivinationCardSambodhisVow",
  "Sanctified Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingLuckyModRolls",
  "Scarab of Adversaries": "Metadata/Items/Scarabs/ScarabMisc2",
  "Scarab of Divinity": "Metadata/Items/Scarabs/ScarabMisc3",
  "Scarab of Monstrous Lineage": "Metadata/Items/Scarabs/ScarabMisc1",
  "Scarab of Radiant Storms": "Metadata/Items/Scarabs/ScarabMisc11",
  "Scarab of Stability": "Metadata/Items/Scarabs/ScarabMisc5",
  "Scarab of the Dextral": "Metadata/Items/Scarabs/ScarabMisc10",
  "Scarab of the Sinistral": "Metadata/Items/Scarabs/ScarabMisc9",
  "Scarab of Wisps": "Metadata/Items/Scarabs/ScarabMisc8",
  "Scorched Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingFire",
  "Screaming Essence of Anguish": "Metadata/Items/Currency/CurrencyEssenceAnguish2",
  "Screaming Essence of Doubt": "Metadata/Items/Currency/CurrencyEssenceDoubt3",
  "Screaming Essence of Dread": "Metadata/Items/Currency/CurrencyEssenceDread1",
  "Screaming Essence of Envy": "Metadata/Items/Currency/CurrencyEssenceEnvy1",
  "Screaming Essence of Hatred": "Metadata/Items/Currency/CurrencyEssenceHatred5",
  "Screaming Essence of Loathing": "Metadata/Items/Currency/CurrencyEssenceLoathing2",
  "Screaming Essence of Rage": "Metadata/Items/Currency/CurrencyEssenceRage3",
  "Screaming Essence of Spite": "Metadata/Items/Currency/CurrencyEssenceSpite2",
  "Screaming Essence of Suffering": "Metadata/Items/Currency/CurrencyEssenceSuffering3",
  "Screaming Essence of Woe": "Metadata/Items/Currency/CurrencyEssenceWoe5",
  "Screaming Essence of Wrath": "Metadata/Items/Currency/CurrencyEssenceWrath3",
  "Screaming Essence of Zeal": "Metadata/Items/Currency/CurrencyEssenceZeal2",
  "Scroll of Wisdom": "Metadata/Items/Currency/CurrencyIdentification",
  "Sepia Oil": "Metadata/Items/Currency/Mushrune2",
  "Serrated Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingAttackMods",
  "Seven Years Bad Luck": "Metadata/Items/DivinationCards/DivinationCardSevenYearsBadLuck",
  "Shaper's Exalted Orb": "Metadata/Items/Currency/CurrencyAddModToRareShaper",
  "Shrieking Essence of Anger": "Metadata/Items/Currency/CurrencyEssenceAnger5",
  "Shrieking Essence of Anguish": "Metadata/Items/Currency/CurrencyEssenceAnguish3",
  "Shrieking Essence of Contempt": "Metadata/Items/Currency/CurrencyEssenceContempt6",
  "Shrieking Essence of Doubt": "Metadata/Items/Currency/CurrencyEssenceDoubt4",
  "Shrieking Essence of Dread": "Metadata/Items/Currency/CurrencyEssenceDread2",
  "Shrieking Essence of Envy": "Metadata/Items/Currency/CurrencyEssenceEnvy2",
  "Shrieking Essence of Fear": "Metadata/Items/Currency/CurrencyEssenceFear5",
  "Shrieking Essence of Greed": "Metadata/Items/Currency/CurrencyEssenceGreed6",
  "Shrieking Essence of Hatred": "Metadata/Items/Currency/CurrencyEssenceHatred6",
  "Shrieking Essence of Loathing": "Metadata/Items/Currency/CurrencyEssenceLoathing3",
  "Shrieking Essence of Misery": "Metadata/Items/Currency/CurrencyEssenceMisery2",
  "Shrieking Essence of Rage": "Metadata/Items/Currency/CurrencyEssenceRage4",
  "Shrieking Essence of Scorn": "Metadata/Items/Currency/CurrencyEssenceScorn2",
  "Shrieking Essence of Sorrow": "Metadata/Items/Currency/CurrencyEssenceSorrow5",
  "Shrieking Essence of Spite": "Metadata/Items/Currency/CurrencyEssenceSpite3",
  "Shrieking Essence of Suffering": "Metadata/Items/Currency/CurrencyEssenceSuffering4",
  "Shrieking Essence of Torment": "Metadata/Items/Currency/CurrencyEssenceTorment5",
  "Shrieking Essence of Woe": "Metadata/Items/Currency/CurrencyEssenceWoe6",
  "Shrieking Essence of Wrath": "Metadata/Items/Currency/CurrencyEssenceWrath4",
  "Shrieking Essence of Zeal": "Metadata/Items/Currency/CurrencyEssenceZeal3",
  "Shuddering Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingSpeed",
  "Silver Oil": "Metadata/Items/Currency/Mushrune11",
  "Simulacrum": "Metadata/Items/MapFragments/CurrencyAfflictionFragment",
  "Simulacrum Splinter": "Metadata/Items/Currency/CurrencyAfflictionShard",
  "Singular Delirium Orb": "Metadata/Items/Currency/CurrencyAfflictionOrbUniques",
  "Skittering Delirium Orb": "Metadata/Items/Currency/CurrencyAfflictionOrbScarabs",
  "Something Dark": "Metadata/Items/DivinationCards/DivinationCardSomethingDark",
  "Stacked Deck": "Metadata/Items/DivinationCards/DivinationCardDeck",
  "Succor of the Sinless": "Metadata/Items/DivinationCards/DivinationCardSuccorOfTheSinless",
  "Sulphite Scarab": "Metadata/Items/Scarabs/ScarabSulphiteNew1",
  "Sulphite Scarab of Fumes": "Metadata/Items/Scarabs/ScarabSulphiteNew3",
  "Syndicate Medallion": "Metadata/Items/MapFragments/CurrencyMastermindsLair",
  "Synthesising Fragment": "Metadata/Items/MapFragments/CurrencyUberBossKeyCortex",
  "Tailoring Orb": "Metadata/Items/Currency/CurrencyHeistArmourEnchant",
  "Tainted Armourer's Scrap": "Metadata/Items/Currency/CurrencyHellscapeArmourQuality",
  "Tainted Blacksmith's Whetstone": "Metadata/Items/Currency/CurrencyHellscapeWeaponQuality",
  "Tainted Catalyst": "Metadata/Items/Currency/CurrencyJewelleryQualityVaal",
  "Tainted Chaos Orb": "Metadata/Items/Currency/CurrencyHellscapeRerollRare",
  "Tainted Chromatic Orb": "Metadata/Items/Currency/CurrencyHellscapeRerollSocketColours",
  "Tainted Divine Teardrop": "Metadata/Items/Currency/CurrencyHellscapeUpgradeModTier",
  "Tainted Exalted Orb": "Metadata/Items/Currency/CurrencyHellscapeAddModToRare",
  "Tainted Jeweller's Orb": "Metadata/Items/Currency/CurrencyHellscapeRerollSocketNumbers",
  "Tainted Mythic Orb": "Metadata/Items/Currency/CurrencyHellscapeUpgradeToUnique",
  "Tainted Oil": "Metadata/Items/Currency/MushruneCorrupt",
  "Tainted Orb of Fusing": "Metadata/Items/Currency/CurrencyHellscapeRerollSocketLinks",
  "Tangled Fossil": "Metadata/Items/Currency/CurrencyDelveCraftingRandom",
  "Tattoo of the Arohongui Moonwarden": "Metadata/Items/Currency/AncestralTattooArohongui1",
  "Tattoo of the Arohongui Scout": "Metadata/Items/Currency/AncestralTattooArohongui2",
  "Tattoo of the Arohongui Shaman": "Metadata/Items/Currency/AncestralTattooArohongui5",
  "Tattoo of the Arohongui Warmonger": "Metadata/Items/Currency/AncestralTattooArohongui4",
  "Tattoo of the Arohongui Warrior": "Metadata/Items/Currency/AncestralTattooArohongui3",
  "Tattoo of the Hinekora Deathwarden": "Metadata/Items/Currency/AncestralTattooHinekora2",
  "Tattoo of the Hinekora Shaman": "Metadata/Items/Currency/AncestralTattooHinekora3",
  "Tattoo of the Hinekora Storyteller": "Metadata/Items/Currency/AncestralTattooHinekora4",
  "Tattoo of the Hinekora Warmonger": "Metadata/Items/Currency/AncestralTattooHinekora5",
  "Tattoo of the Hinekora Warrior": "Metadata/Items/Currency/AncestralTattooHinekora1",
  "Tattoo of the Kitava Blood Drinker": "Metadata/Items/Currency/AncestralTattooKitava1",
  "Tattoo of the Kitava Heart Eater": "Metadata/Items/Currency/AncestralTattooKitava4",
  "Tattoo of the Kitava Rebel": "Metadata/Items/Currency/AncestralTattooKitava2",
  "Tattoo of the Kitava Shaman": "Metadata/Items/Currency/AncestralTattooKitava5",
  "Tattoo of the Kitava Warrior": "Metadata/Items/Currency/AncestralTattooKitava3",
  "Tattoo of the Ngamahu Firewalker": "Metadata/Items/Currency/AncestralTattooNgamahu1",
  "Tattoo of the Ngamahu Shaman": "Metadata/Items/Currency/AncestralTattooNgamahu2",
  "Tattoo of the Ngamahu Warmonger": "Metadata/Items/Currency/AncestralTattooNgamahu4",
  "Tattoo of the Ngamahu Warrior": "Metadata/Items/Currency/AncestralTattooNgamahu3",
  "Tattoo of the Ngamahu Woodcarver": "Metadata/Items/Currency/AncestralTattooNgamahu5",
  "Tattoo of the Ramako Archer": "Metadata/Items/Currency/AncestralTattooRamako2",
  "Tattoo of the Ramako Fleetfoot": "Metadata/Items/Currency/AncestralTattooRamako4",
  "Tattoo of the Ramako Scout": "Metadata/Items/Currency/AncestralTattooRamako1",
  "Tattoo of the Ramako Shaman": "Metadata/Items/Currency/AncestralTattooRamako5",
  "Tattoo of the Ramako Sniper": "Metadata/Items/Currency/AncestralTattooRamako3",
  "Tattoo of the Rongokurai Guard": "Metadata/Items/Currency/AncestralTattooRongokurai5",
  "Tattoo of the Rongokurai Turtle": "Metadata/Items/Currency/AncestralTattooRongokurai4",
  "Tattoo of the Rongokurai Warrior": "Metadata/Items/Currency/AncestralTattooRongokurai1",
  "Tattoo of the Tasalio Bladedancer": "Metadata/Items/Currency/AncestralTattooTasalio1",
  "Tattoo of the Tasalio Scout": "Metadata/Items/Currency/AncestralTattooTasalio5",
  "Tattoo of the Tasalio Shaman": "Metadata/Items/Currency/AncestralTattooTasalio3",
  "Tattoo of the Tasalio Tideshifter": "Metadata/Items/Currency/AncestralTattooTasalio2",
  "Tattoo of the Tasalio Warrior": "Metadata/Items/Currency/AncestralTattooTasalio4",
  "Tattoo of the Tawhoa Herbalist": "Metadata/Items/Currency/AncestralTattooTawhoa4",
  "Tattoo of the Tawhoa Scout": "Metadata/Items/Currency/AncestralTattooTawhoa2",
  "Tattoo of the Tawhoa Shaman": "Metadata/Items/Currency/AncestralTattooTawhoa5",
  "Tattoo of the Tawhoa Warrior": "Metadata/Items/Currency/AncestralTattooTawhoa3",
  "Tattoo of the Tukohama Shaman": "Metadata/Items/Currency/AncestralTattooTukohama1",
  "Tattoo of the Tukohama Warcaller": "Metadata/Items/Currency/AncestralTattooTukohama5",
  "Tattoo of the Tukohama Warmonger": "Metadata/Items/Currency/AncestralTattooTukohama4",
  "Tattoo of the Valako Scout": "Metadata/Items/Currency/AncestralTattooValako2",
  "Tattoo of the Valako Shaman": "Metadata/Items/Currency/AncestralTattooValako5",
  "Tattoo of the Valako Shieldbearer": "Metadata/Items/Currency/AncestralTattooValako4",
  "Tattoo of the Valako Stormrider": "Metadata/Items/Currency/AncestralTattooValako1",
  "Tattoo of the Valako Warrior": "Metadata/Items/Currency/AncestralTattooValako3",
  "Teal Oil": "Metadata/Items/Currency/Mushrune5",
  "Telesia's Ducat": "Metadata/Items/Deepwater/DeepwaterChartReroll",
  "Tempering Catalyst": "Metadata/Items/Currency/CurrencyJewelleryQualityDefense",
  "Tempering Orb": "Metadata/Items/Currency/CurrencyHeistWeaponEnchant",
  "Templar Astrolabe": "Metadata/Items/Currency/AstrolabeGeneric",
  "Templar Enshrouding Crystal": "Metadata/Items/Currency/LegionCocoonShield",
  "Thaumaturge's Delirium Orb": "Metadata/Items/Currency/CurrencyAfflictionOrbGems",
  "The Apothecary": "Metadata/Items/DivinationCards/DivinationCardTheApothecary",
  "The Artist": "Metadata/Items/DivinationCards/DivinationCardTheArtist",
  "The Bitter Blossom": "Metadata/Items/DivinationCards/DivinationCardTheBitterBlossom",
  "The Celestial Justicar": "Metadata/Items/DivinationCards/DivinationCardTheCelestialJusticar",
  "The Changeling's Ducat": "Metadata/Items/Deepwater/DeepwaterBlankCurrency",
  "The Chosen": "Metadata/Items/DivinationCards/DivinationCardTheChosen",
  "The Conduit": "Metadata/Items/DivinationCards/DivinationCardTheConduit",
  "The Craving": "Metadata/Items/DivinationCards/DivinationCardTheCraving",
  "The Demon": "Metadata/Items/DivinationCards/DivinationCardTheDemon",
  "The Destination": "Metadata/Items/DivinationCards/DivinationCardTheDestination",
  "The Doctor": "Metadata/Items/DivinationCards/DivinationCardTheDoctor",
  "The Doppelganger": "Metadata/Items/DivinationCards/DivinationCardTheDoppelganger",
  "The Dragon's Heart": "Metadata/Items/DivinationCards/DivinationCardTheDragonsHeart",
  "The Dreamer": "Metadata/Items/DivinationCards/DivinationCardTheDreamer",
  "The Dreamland": "Metadata/Items/DivinationCards/DivinationCardTheDreamland",
  "The Eldritch Decay": "Metadata/Items/DivinationCards/DivinationCardTheEldritchDecay",
  "The Endurance": "Metadata/Items/DivinationCards/DivinationCardTheEndurance",
  "The Enlightened": "Metadata/Items/DivinationCards/DivinationCardTheEnlightened",
  "The Escape": "Metadata/Items/DivinationCards/DivinationCardTheEscape",
  "The Eternal War": "Metadata/Items/DivinationCards/DivinationCardTheEternalWar",
  "The Everlasting": "Metadata/Items/DivinationCards/DivinationCardTheEverlasting",
  "The Explorer": "Metadata/Items/DivinationCards/DivinationCardTheExplorer",
  "The Eye of Terror": "Metadata/Items/DivinationCards/DivinationCardTheEyeOfTerror",
  "The Eye of the Dragon": "Metadata/Items/DivinationCards/DivinationCardTheEyeOfTheDragon",
  "The Fiend": "Metadata/Items/DivinationCards/DivinationCardTheFiend",
  "The Finishing Touch": "Metadata/Items/DivinationCards/DivinationCardTheFinishingTouch",
  "The Fishmonger": "Metadata/Items/DivinationCards/DivinationCardTheFishmonger",
  "The Flora's Gift": "Metadata/Items/DivinationCards/DivinationCardTheFlorasGift",
  "The Forbidden Fruit": "Metadata/Items/DivinationCards/DivinationCardTheForbiddenFruit",
  "The Forgotten Treasure": "Metadata/Items/DivinationCards/DivinationCardTheForgottenTreasure",
  "The Fortunate": "Metadata/Items/DivinationCards/DivinationCardTheFortunate",
  "The Forward Gaze": "Metadata/Items/DivinationCards/DivinationCardTheForwardGaze",
  "The Garish Power": "Metadata/Items/DivinationCards/DivinationCardTheGarishPower",
  "The Genteel's Ducat": "Metadata/Items/Deepwater/DeepwaterAttributeSwap",
  "The Gulf": "Metadata/Items/DivinationCards/DivinationCardTheGulf",
  "The Hook": "Metadata/Items/DivinationCards/DivinationCardTheHook",
  "The Immortal": "Metadata/Items/DivinationCards/DivinationCardTheImmortal",
  "The Jester": "Metadata/Items/DivinationCards/DivinationCardTheJester",
  "The King's Heart": "Metadata/Items/DivinationCards/DivinationCardTheKingsHeart",
  "The Lake": "Metadata/Items/DivinationCards/DivinationCardTheLake",
  "The Last One Standing": "Metadata/Items/DivinationCards/DivinationCardTheLastOneStanding",
  "The Last Supper": "Metadata/Items/DivinationCards/DivinationCardTheLastSupper",
  "The Mad King": "Metadata/Items/DivinationCards/DivinationCardTheMadKing",
  "The Maven's Writ": "Metadata/Items/MapFragments/CurrencyMavenKey",
  "The Miracle": "Metadata/Items/DivinationCards/DivinationCardTheMiracle",
  "The Nurse": "Metadata/Items/DivinationCards/DivinationCardTheNurse",
  "The One With All": "Metadata/Items/DivinationCards/DivinationCardTheOneWithAll",
  "The Opulent": "Metadata/Items/DivinationCards/DivinationCardTheOpulecent",
  "The Patient": "Metadata/Items/DivinationCards/DivinationCardThePatient",
  "The Poet": "Metadata/Items/DivinationCards/DivinationCardThePoet",
  "The Price of Devotion": "Metadata/Items/DivinationCards/DivinationCardThePriceOfDevotion",
  "The Prince of Darkness": "Metadata/Items/DivinationCards/DivinationCardThePrinceOfDarkness",
  "The Progeny of Lunaris": "Metadata/Items/DivinationCards/DivinationCardTheProgenyOfLunaris",
  "The Scout": "Metadata/Items/DivinationCards/DivinationCardTheScout",
  "The Sephirot": "Metadata/Items/DivinationCards/DivinationCardTheSephirot",
  "The Shepherd's Sandals": "Metadata/Items/DivinationCards/DivinationCardTheShepherdsSandals",
  "The Shieldbearer": "Metadata/Items/DivinationCards/DivinationCardTheShieldbearer",
  "The Silly Boy": "Metadata/Items/DivinationCards/DivinationCardTheSillyBoy",
  "The Slumbering Beast": "Metadata/Items/DivinationCards/DivinationCardTheSlumberingBeast",
  "The Soul": "Metadata/Items/DivinationCards/DivinationCardTheSoul",
  "The Traitor": "Metadata/Items/DivinationCards/DivinationCardTheTraitor",
  "The Undaunted": "Metadata/Items/DivinationCards/DivinationCardTheUndaunted",
  "The Unexpected Prize": "Metadata/Items/DivinationCards/DivinationCardTheUnexpectedPrize",
  "The Union": "Metadata/Items/DivinationCards/DivinationCardTheUnion",
  "The Vast": "Metadata/Items/DivinationCards/DivinationCardTheVast",
  "The Void": "Metadata/Items/DivinationCards/DivinationCardTheVoid",
  "The Wilted Rose": "Metadata/Items/DivinationCards/DivinationCardTheWiltedRose",
  "The Wolf's Legacy": "Metadata/Items/DivinationCards/DivinationCardTheWolfsLegacy",
  "The Wrath": "Metadata/Items/DivinationCards/DivinationCardTheWrath",
  "The Wretched": "Metadata/Items/DivinationCards/DivinationCardTheWretched",
  "Three Faces in the Dark": "Metadata/Items/DivinationCards/DivinationCardThreeFacesInTheDark",
  "Time-Lost Relic": "Metadata/Items/DivinationCards/DivinationCardTimeLostRelic",
  "Timeless Astrolabe": "Metadata/Items/Currency/AstrolabeLegion",
  "Timeless Eternal Emblem": "Metadata/Items/MapFragments/CurrencyLegionFragmentEternal",
  "Timeless Eternal Empire Splinter": "Metadata/Items/Currency/CurrencyLegionEternalEmpireShard",
  "Timeless Karui Emblem": "Metadata/Items/MapFragments/CurrencyLegionFragmentKarui",
  "Timeless Karui Splinter": "Metadata/Items/Currency/CurrencyLegionKaruiShard",
  "Timeless Maraketh Emblem": "Metadata/Items/MapFragments/CurrencyLegionFragmentMaraketh",
  "Timeless Templar Emblem": "Metadata/Items/MapFragments/CurrencyLegionFragmentTemplar",
  "Timeless Vaal Emblem": "Metadata/Items/MapFragments/CurrencyLegionFragmentVaal",
  "Timeless Vaal Splinter": "Metadata/Items/Currency/CurrencyLegionVaalShard",
  "Titanic Scarab": "Metadata/Items/Scarabs/ScarabUniquesNew1",
  "Titanic Scarab of Legend": "Metadata/Items/Scarabs/ScarabUniquesNew3",
  "Titanic Scarab of Treasures": "Metadata/Items/Scarabs/ScarabUniquesNew2",
  "Torment Scarab": "Metadata/Items/Scarabs/ScarabTormentNew1",
  "Torment Scarab of Peculiarity": "Metadata/Items/Scarabs/ScarabTormentNew2",
  "Torment Scarab of Possession": "Metadata/Items/Scarabs/ScarabTormentNew4",
  "Tranquillity": "Metadata/Items/DivinationCards/DivinationCardTranquillity",
  "Transmutation Shard": "Metadata/Items/Currency/CurrencyUpgradeToMagicShard",
  "Trarthan Scarab": "Metadata/Items/Scarabs/ScarabMercenaries1",
  "Trarthan Scarab of Infamy": "Metadata/Items/Scarabs/ScarabMercenaries2",
  "Trarthan Scarab of Renown": "Metadata/Items/Scarabs/ScarabMercenaries3",
  "Trarthan Scarab of Surprising Alliances": "Metadata/Items/Scarabs/ScarabMercenaries4",
  "Traumatic Fragment": "Metadata/Items/MapFragments/CurrencyUberBossKeyAnger",
  "Tribute to the Goddess": "Metadata/Items/MapFragments/CurrencyOfferingToTheGoddessTribute",
  "Turbulent Catalyst": "Metadata/Items/Currency/CurrencyJewelleryQualityElemental",
  "Tzamoto's Ducat": "Metadata/Items/Deepwater/DeepwaterGhostbuster",
  "Ukatoa's Ducat": "Metadata/Items/Deepwater/DeepwaterEldritch",
  "Ultimatum Scarab": "Metadata/Items/Scarabs/ScarabUltimatum1",
  "Ultimatum Scarab of Bribing": "Metadata/Items/Scarabs/ScarabUltimatum2",
  "Ultimatum Scarab of Catalysing": "Metadata/Items/Scarabs/ScarabUltimatum4",
  "Ultimatum Scarab of Dueling": "Metadata/Items/Scarabs/ScarabUltimatum3",
  "Ultimatum Scarab of Inscription": "Metadata/Items/Scarabs/ScarabUltimatum5",
  "Unrequited Love": "Metadata/Items/DivinationCards/DivinationCardUnrequitedLove",
  "Unstable Catalyst": "Metadata/Items/Currency/CurrencyJewelleryQualityCritical",
  "Vaal Enshrouding Crystal": "Metadata/Items/Currency/LegionCocoonHelmet",
  "Vaal Orb": "Metadata/Items/Currency/CurrencyCorrupt",
  "Valdo's Puzzle Box": "Metadata/Items/Currency/CurrencyValdoPuzzleBox",
  "Veiled Chaos Orb": "Metadata/Items/Currency/CurrencyRerollRareVeiledChaos",
  "Veiled Exalted Orb": "Metadata/Items/Currency/CurrencyRerollRareVeiled",
  "Verdant Oil": "Metadata/Items/Currency/Mushrune4",
  "Veritania's Crest": "Metadata/Items/MapFragments/CurrencySirusFragment4",
  "Vinia's Token": "Metadata/Items/DivinationCards/DivinationCardViniasToken",
  "Violet Oil": "Metadata/Items/Currency/Mushrune7",
  "Vivid Crystallised Lifeforce": "Metadata/Items/Currency/HarvestSeedGreen",
  "Volatile Vaal Orb": "Metadata/Items/Currency/CurrencyHellscapeModValues",
  "Wailing Essence of Doubt": "Metadata/Items/Currency/CurrencyEssenceDoubt2",
  "Wailing Essence of Fear": "Metadata/Items/Currency/CurrencyEssenceFear3",
  "Wailing Essence of Rage": "Metadata/Items/Currency/CurrencyEssenceRage2",
  "Wailing Essence of Spite": "Metadata/Items/Currency/CurrencyEssenceSpite1",
  "Wailing Essence of Woe": "Metadata/Items/Currency/CurrencyEssenceWoe4",
  "Warlord's Exalted Orb": "Metadata/Items/AtlasExiles/AddModToRareWarlord",
  "Wealth and Power": "Metadata/Items/DivinationCards/DivinationCardWealthAndPower",
  "Weeping Essence of Doubt": "Metadata/Items/Currency/CurrencyEssenceDoubt1",
  "Weeping Essence of Fear": "Metadata/Items/Currency/CurrencyEssenceFear2",
  "Weeping Essence of Hatred": "Metadata/Items/Currency/CurrencyEssenceHatred3",
  "Weeping Essence of Suffering": "Metadata/Items/Currency/CurrencyEssenceSuffering1",
  "Weeping Essence of Woe": "Metadata/Items/Currency/CurrencyEssenceWoe3",
  "Whispering Delirium Orb": "Metadata/Items/Currency/CurrencyAfflictionOrbEssences",
  "Whispering Essence of Woe": "Metadata/Items/Currency/CurrencyEssenceWoe1",
  "Wild Crystallised Lifeforce": "Metadata/Items/Currency/HarvestSeedRed",
  "Zorath's Eye of Authority": "Metadata/Items/MapFragments/AbyssPinnacleKeySearching",
  "Zorath's Eye of Malevolence": "Metadata/Items/MapFragments/AbyssPinnacleKeyMurderous",
  "Zorath's Eye of the Endless": "Metadata/Items/MapFragments/AbyssPinnacleKeyGhastly",
  "Zorath's Eye of the Inevitable": "Metadata/Items/MapFragments/AbyssPinnacleKeyHypnotic",
};

export function isFaustusTradeable(name: string): boolean {
  return Object.prototype.hasOwnProperty.call(FAUSTUS_NAME_TO_ID, name);
}

interface ExchangeMarket {
  league: string;
  market_pair: [string, string];
  volume_traded: Record<string, number>;
  lowest_stock: Record<string, number>;
  highest_stock: Record<string, number>;
  lowest_ratio: Record<string, number>;
  highest_ratio: Record<string, number>;
}

interface CacheEntry {
  data: ExchangeMarket[];
  expiresAt: number;
}
const cache = new Map<string, CacheEntry>();

/**
 * The endpoint's own docs say responses are "purely historical" - there isn't any way to get data
 * from the current, still-open hour - and that an omitted id defaults to the FIRST retained hour
 * (2024-era, verified during development), not the most recent one. Two hours back is comfortably
 * inside a fully-closed hour while staying as fresh as the endpoint allows.
 */
async function fetchExchangeMarkets(league: string): Promise<ExchangeMarket[]> {
  const cached = cache.get(league);
  if (cached && cached.expiresAt > Date.now()) return cached.data;

  const hourTimestamp = Math.floor(Date.now() / 1000 / 3600) * 3600 - 2 * 3600;
  try {
    const res = await fetch(`${EXCHANGE_URL}/${hourTimestamp}`, { headers: { "User-Agent": USER_AGENT } });
    if (!res.ok) {
      console.warn(`GGG currency-exchange request failed (${res.status})`);
      return cached?.data ?? [];
    }
    const data = (await res.json()) as { markets?: ExchangeMarket[] };
    const markets = (data.markets ?? []).filter((m) => m.league === league);
    cache.set(league, { data: markets, expiresAt: Date.now() + CACHE_TTL_MS });
    return markets;
  } catch (err) {
    console.warn("GGG currency-exchange request errored:", err);
    return cached?.data ?? [];
  }
}

/** Chaos-per-unit rate for `id`, using the pair's ratio midpoint - undefined if `id` isn't one side of this pair. */
function rateFromPair(market: ExchangeMarket, id: string, chaosSideId: string): number | undefined {
  if (!market.market_pair.includes(id) || !market.market_pair.includes(chaosSideId)) return undefined;
  const idLow = market.lowest_ratio[id];
  const idHigh = market.highest_ratio[id];
  const chaosLow = market.lowest_ratio[chaosSideId];
  const chaosHigh = market.highest_ratio[chaosSideId];
  if (!idLow || !idHigh || !chaosLow || !chaosHigh) return undefined;
  // lowest_ratio and highest_ratio are each a SELF-CONTAINED quote (both sides describe one
  // observed ratio), not independent per-side extremes to mix across - confirmed against a live
  // in-game quote (Dead Man's Sulphur, a bulk currency GGG bug report traced this to): the API's
  // lowest_ratio {chaos:1, sulphur:135} and highest_ratio {chaos:71, sulphur:6800} match the
  // in-game instant-sell (~137 sulphur/chaos) and instant-buy (~101 sulphur/chaos) prices closely
  // when each pair's OWN two sides are divided together. Cross-matching them instead (chaosLow
  // against idHigh, as this used to do) is only harmless when one side happens to always be
  // normalized to 1 (e.g. Divine Orb) - for anything whose ratio scales on both sides, it produces
  // a rate off by orders of magnitude (0.0001c-0.5c here, against a real ~0.007c-0.01c).
  return (chaosLow / idLow + chaosHigh / idHigh) / 2;
}

export interface FaustusPrice {
  chaosValue: number;
  /** Undefined only if Divine Orb itself had no computable rate this hour. */
  divineValue?: number;
}

/**
 * Every FAUSTUS_NAME_TO_ID entry this league's exchange data can actually price, in one shot - one
 * fetch (cached) covers every name, since the whole mapped set is small. Prefers, per name, whichever
 * pair (against Chaos or against Divine, converted) saw the most trade volume that hour, so a
 * thinly-traded coincidental pairing doesn't win over the real market.
 */
export async function getFaustusPrices(league: string): Promise<Map<string, FaustusPrice>> {
  const markets = await fetchExchangeMarkets(league);
  const result = new Map<string, FaustusPrice>();
  if (markets.length === 0) return result;

  let divineChaosRate: number | undefined;
  for (const m of markets) {
    const rate = rateFromPair(m, DIVINE_ID, CHAOS_ID);
    if (rate !== undefined) {
      divineChaosRate = rate;
      break;
    }
  }

  for (const [name, id] of Object.entries(FAUSTUS_NAME_TO_ID)) {
    // Chaos Orb is the pivot currency - it never forms a pair with itself, so it has to be special-cased.
    if (id === CHAOS_ID) {
      result.set(name, { chaosValue: 1, divineValue: divineChaosRate ? 1 / divineChaosRate : undefined });
      continue;
    }
    let best: { chaosValue: number; volume: number } | undefined;
    for (const m of markets) {
      const volume = m.volume_traded[id] ?? 0;
      const viaChaos = rateFromPair(m, id, CHAOS_ID);
      const viaDivine = divineChaosRate !== undefined ? rateFromPair(m, id, DIVINE_ID) : undefined;
      const chaosValue = viaChaos ?? (viaDivine !== undefined ? viaDivine * divineChaosRate! : undefined);
      if (chaosValue !== undefined && (!best || volume > best.volume)) {
        best = { chaosValue, volume };
      }
    }
    if (best) {
      result.set(name, {
        chaosValue: best.chaosValue,
        divineValue: divineChaosRate ? best.chaosValue / divineChaosRate : undefined,
      });
    }
  }
  return result;
}

/** Single-name convenience wrapper for the on-demand "Faustus Price" button - still goes through
 *  the same cached, whole-league computation above rather than re-fetching per click. */
export async function getFaustusPrice(name: string, league: string): Promise<FaustusPrice | undefined> {
  if (!isFaustusTradeable(name)) return undefined;
  const prices = await getFaustusPrices(league);
  return prices.get(name);
}

export interface FaustusSpread {
  name: string;
  /** Cheapest chaos-per-unit rate this pair traded at during the hour - the price you'd have paid
   *  to acquire one. */
  buyChaosValue: number;
  /** Priciest chaos-per-unit rate this pair traded at the same hour - the price you'd have gotten
   *  selling one. Same "purely historical, ~2h stale" caveat as getFaustusPrices - this is the
   *  range trades actually occurred at within one closed hour, not two live standing orders, so a
   *  wide spread is a real signal the price moved, not a guaranteed instant round-trip today. */
  sellChaosValue: number;
  buyDivineValue?: number;
  sellDivineValue?: number;
  /** (sell/buy - 1) * 100. */
  spreadPercent: number;
  /** sell - buy, in chaos, per unit. */
  spreadChaosValue: number;
  /** Chaos Orb volume traded on this pair that hour - how much value actually changed hands, the
   *  primary liquidity signal (a wide spread on a market with near-zero volume isn't fillable). */
  volumeChaos: number;
  /** The item's own unit volume traded that hour. */
  volumeItem: number;
  /** Units of the item listed for trade (highest_stock reached that hour) - the "offers available"
   *  to buy: a depth signal distinct from volume, since volume is what actually traded and this is
   *  what's sitting there right now available to trade against. */
  itemStock: number;
  /** Chaos Orb listed on the other side of this same pair (highest_stock reached that hour) - the
   *  "offers available" to sell into: how much chaos liquidity exists to absorb a sell order. */
  chaosStock: number;
  /** Gold cost to place a buy order for one unit - see lib/faustus-gold.ts. Undefined when that
   *  table doesn't cover this item at all (a genuine gap, not a zero cost). */
  goldCost?: GoldCost;
}

/**
 * Buy/sell spread for every Faustus-tradeable item that has a market this hour, either directly
 * against Chaos Orb or (for items GGG's exchange never opens a Chaos pair for at all - Mirror of
 * Kalandra, Hinekora's Lock, ...) against Divine Orb, converted through that same hour's Divine/
 * Chaos rate. Same "steady price, real market" question getFaustusPrices already answers, but
 * keeping both ends of the hour's trade range instead of collapsing them to one midpoint. The
 * direct Chaos pair is always preferred when one exists - the vast majority of mapped items (515 of
 * 657, checked live) have one - since converting through a second market compounds its own
 * uncertainty into the number; the Divine path only runs at all when no Chaos pair was found.
 */
export async function getFaustusSpreads(league: string): Promise<FaustusSpread[]> {
  const markets = await fetchExchangeMarkets(league);
  if (markets.length === 0) return [];

  let divineChaosRate: number | undefined;
  for (const m of markets) {
    const rate = rateFromPair(m, DIVINE_ID, CHAOS_ID);
    if (rate !== undefined) {
      divineChaosRate = rate;
      break;
    }
  }

  const results: FaustusSpread[] = [];
  for (const [name, id] of Object.entries(FAUSTUS_NAME_TO_ID)) {
    if (id === CHAOS_ID) continue; // Chaos Orb has no spread against itself.

    let best:
      | { buy: number; sell: number; volumeChaos: number; volumeItem: number; itemStock: number; chaosStock: number }
      | undefined;
    for (const m of markets) {
      if (!m.market_pair.includes(id) || !m.market_pair.includes(CHAOS_ID)) continue;
      const idLow = m.lowest_ratio[id];
      const idHigh = m.highest_ratio[id];
      const chaosLow = m.lowest_ratio[CHAOS_ID];
      const chaosHigh = m.highest_ratio[CHAOS_ID];
      if (!idLow || !idHigh || !chaosLow || !chaosHigh) continue;
      // Two chaos-per-unit bounds from the hour's observed ratio range - each of lowest_ratio/
      // highest_ratio is its own self-contained quote (divide its two sides together), never
      // cross-matched against the other extremum's sides - see rateFromPair's comment for why.
      const a = chaosLow / idLow;
      const b = chaosHigh / idHigh;
      const volumeChaos = m.volume_traded[CHAOS_ID] ?? 0;
      // Prefer whichever pair saw the most Chaos volume, same tie-break as getFaustusPrices.
      if (!best || volumeChaos > best.volumeChaos) {
        best = {
          buy: Math.min(a, b),
          sell: Math.max(a, b),
          volumeChaos,
          volumeItem: m.volume_traded[id] ?? 0,
          itemStock: m.highest_stock[id] ?? 0,
          chaosStock: m.highest_stock[CHAOS_ID] ?? 0,
        };
      }
    }

    // Fallback for items with no direct Chaos market this hour - a handful of very high-value
    // items (Mirror of Kalandra, Hinekora's Lock) only ever trade against Divine Orb; GGG's
    // exchange doesn't open every pair for every item. Same "each extremum is its own
    // self-contained quote" math as above, converted through this hour's Divine/Chaos rate rather
    // than skipping the item entirely. volumeChaos/chaosStock become chaos-EQUIVALENT (Divine
    // volume/stock multiplied through the same rate) rather than literal Chaos Orb activity, so
    // the Liquidity column's chaos-denominated thresholds still mean the same thing across both
    // origins - noted here since nothing in the returned shape distinguishes the two paths.
    if (!best && divineChaosRate !== undefined && id !== DIVINE_ID) {
      for (const m of markets) {
        if (!m.market_pair.includes(id) || !m.market_pair.includes(DIVINE_ID)) continue;
        const idLow = m.lowest_ratio[id];
        const idHigh = m.highest_ratio[id];
        const divLow = m.lowest_ratio[DIVINE_ID];
        const divHigh = m.highest_ratio[DIVINE_ID];
        if (!idLow || !idHigh || !divLow || !divHigh) continue;
        const a = (divLow / idLow) * divineChaosRate;
        const b = (divHigh / idHigh) * divineChaosRate;
        const volumeDivine = m.volume_traded[DIVINE_ID] ?? 0;
        const volumeChaos = volumeDivine * divineChaosRate;
        if (!best || volumeChaos > best.volumeChaos) {
          best = {
            buy: Math.min(a, b),
            sell: Math.max(a, b),
            volumeChaos,
            volumeItem: m.volume_traded[id] ?? 0,
            itemStock: m.highest_stock[id] ?? 0,
            chaosStock: (m.highest_stock[DIVINE_ID] ?? 0) * divineChaosRate,
          };
        }
      }
    }

    if (!best || !(best.buy > 0)) continue;

    results.push({
      name,
      buyChaosValue: best.buy,
      sellChaosValue: best.sell,
      buyDivineValue: divineChaosRate ? best.buy / divineChaosRate : undefined,
      sellDivineValue: divineChaosRate ? best.sell / divineChaosRate : undefined,
      spreadPercent: (best.sell / best.buy - 1) * 100,
      spreadChaosValue: best.sell - best.buy,
      volumeChaos: best.volumeChaos,
      volumeItem: best.volumeItem,
      itemStock: best.itemStock,
      chaosStock: best.chaosStock,
      goldCost: goldCostFor(name, id),
    });
  }
  return results;
}
