/**
 * Gold cost of trading an item on GGG's Currency Exchange (the "Faustus" NPC).
 *
 * GGG's exchange API carries no gold/fee field at all (checked every key across every market in
 * the live response), and there's no machine-readable source for it either, so this table is
 * transcribed by hand from poedb.tw's Currency Exchange page
 * (https://poedb.tw/us/Currency_Exchange), which lists a specific per-item gold cost for
 * essentially every exchange-tradeable item - the user pulled the page's full, untruncated content
 * directly (an earlier automated fetch of the same page cut off partway through, before Oils/
 * Catalysts/Omens/Tattoos/Delirium Orbs/most Fragments - those categories are now filled in from
 * that same complete pull). Needs updating by hand if poedb's numbers change.
 *
 * Every mapping below is grounded in a real display name from docs/faustus-mapping.md (generated
 * from RePoE - see lib/faustus.ts's header) - nothing here is a guess about which name a value
 * applies to; a source name that doesn't match a real name here is simply never used (poedb's own
 * page lists a handful of names from removed/old content that don't match anything current). Two
 * honest gaps are marked explicitly rather than papered over:
 *   - `approximate: true` - a handful of Divination Cards poedb's page doesn't cover fall back to
 *     the PoE wiki's 15-1850 family range (a full per-card cross-reference wasn't completed).
 *   - `undefined` (no gold shown at all) - neither source names this item at all.
 */

export interface GoldCost {
  /** Gold charged per single item bought. Fractional for items priced per-stack (e.g. lifeforce). */
  perItem: number;
  /** True when the source only gives a range/family estimate rather than this exact item's cost. */
  approximate: boolean;
  /** Shown on hover when approximate, explaining what the estimate is based on. */
  note?: string;
}

const exact = (perItem: number): GoldCost => ({ perItem, approximate: false });
const approx = (perItem: number, note: string): GoldCost => ({ perItem, approximate: true, note });

/** Individually-named items with a single, unambiguous cost (poedb.tw unless noted). */
const EXACT_COSTS: Readonly<Record<string, number>> = {
  // --- Basic currency ---
  "Portal Scroll": 1,
  "Scroll of Wisdom": 1,
  "Orb of Transmutation": 3,
  "Orb of Augmentation": 5,
  "Orb of Chance": 10,
  "Orb of Alteration": 10,
  "Jeweller's Orb": 10,
  "Chromatic Orb": 20,
  "Orb of Fusing": 15,
  "Orb of Alchemy": 15,
  "Chaos Orb": 15,
  "Orb of Scouring": 15,
  "Orb of Regret": 20,
  "Vaal Orb": 20,
  "Orb of Binding": 20,
  "Instilling Orb": 20,
  "Orb of Unmaking": 20,
  "Blessed Orb": 35,
  "Enkindling Orb": 35,
  "Regal Orb": 20,
  "Divine Vessel": 150,
  "Exalted Orb": 20,
  "Ancient Orb": 250,
  "Stacked Deck": 35,
  "Valdo's Puzzle Box": 300,
  "Divine Orb": 250,
  "Orb of Annulment": 250,
  "Voidborn Reliquary Key": 975,
  "Reflecting Mist": 500,
  "Tempering Orb": 250,
  "Tailoring Orb": 250,
  "Fracturing Orb": 500,
  "Veiled Chaos Orb": 250,
  "Veiled Exalted Orb": 500,
  "Sacred Orb": 250,
  "Hinekora's Lock": 6250,
  "Mirror of Kalandra": 25000,
  "Armourer's Scrap": 25,
  "Blacksmith's Whetstone": 30,
  "Glassblower's Bauble": 50,
  "Gemcutter's Prism": 50,
  // Priced per stack on the source ("1 gold per 8", "1 gold per 1000") rather than per single item.
  "Crystallised Lifeforce": 1 / 8,
  "Sacred Crystallised Lifeforce": 125,
  "Rogue's Marker": 1 / 1000,

  // --- Currency Shards ---
  "Transmutation Shard": 1 / 4,
  "Alchemy Shard": 1,
  "Fracturing Shard": 25,
  "Mirror Shard": 1250,
  "Simulacrum Splinter": 1,

  // --- Eldritch currency (base orbs; tiered ichor/ember handled by pattern below) ---
  "Eldritch Chaos Orb": 525,
  "Eldritch Exalted Orb": 525,
  "Eldritch Orb of Annulment": 525,
  "Orb of Conflict": 1050,

  // --- Influenced currency ---
  "Shaper's Exalted Orb": 500,
  "Elder's Exalted Orb": 500,
  "Crusader's Exalted Orb": 500,
  "Redeemer's Exalted Orb": 500,
  "Hunter's Exalted Orb": 500,
  "Warlord's Exalted Orb": 500,
  "Awakener's Orb": 1000,
  "Orb of Dominance": 1000,
  "Orb of Remembrance": 1000,
  "Orb of Unravelling": 1000,
  "Orb of Intention": 1000,

  // --- Tainted (Hellscape) currency ---
  "Tainted Chromatic Orb": 75,
  "Tainted Jeweller's Orb": 75,
  "Tainted Armourer's Scrap": 75,
  "Tainted Blacksmith's Whetstone": 100,
  "Tainted Orb of Fusing": 150,
  "Tainted Mythic Orb": 200,
  "Tainted Chaos Orb": 375,
  "Tainted Exalted Orb": 575,
  "Tainted Divine Teardrop": 900,
  "Volatile Vaal Orb": 900,
  "Tainted Catalyst": 150, // from the PoE wiki (poedb's page didn't cover Catalysts at all)
  "Tainted Oil": 500, // from the PoE wiki (poedb's page didn't cover Oils at all)

  // --- Maven's Chisels ---
  "Maven's Chisel of Avarice": 200,
  "Maven's Chisel of Divination": 200,
  "Maven's Chisel of Procurement": 200,
  "Maven's Chisel of Proliferation": 200,
  "Maven's Chisel of Scarabs": 200,

  // --- Memories (the plain-currency "Memory of X" line - distinct from the "Echo of X" boss-key
  // fragments under MapFragments/AtlasMemory, which poedb's page didn't cover; see the header note) ---
  "Memory of Loneliness": 1000,
  "Memory of Reverence": 1000,
  "Memory of Trauma": 1000,

  // --- Breach (Foulborn currency) - poedb confirms this exact assignment, resolving what used to
  // be an inferred rarity-ordering guess against the wiki's unassigned 500/750/1000 trio ---
  "Foulborn Orb of Augmentation": 500,
  "Foulborn Regal Orb": 750,
  "Foulborn Exalted Orb": 1000,
  "Flesh of Xesht": 1000,

  // --- Fragments with a single flat value (PoE wiki - poedb's page didn't reach the Fragments
  // section before its content was truncated) ---
  "An Audience With The King": 250,
  Simulacrum: 250,
  "Syndicate Medallion": 250,
  "Sacred Blossom": 250,
  "Ritual Vessel": 250,
  "The Maven's Writ": 1000,
  "Hivebrain Gland": 500,
  "Fragment of the Chimera": 250,
  "Fragment of the Hydra": 250,
  "Fragment of the Minotaur": 250,
  "Fragment of the Phoenix": 250,
  "Fragment of Constriction": 250,
  "Fragment of Enslavement": 250,
  "Fragment of Eradication": 250,
  "Fragment of Purification": 250,
  "Al-Hezmin's Crest": 250,
  "Baran's Crest": 250,
  "Drox's Crest": 250,
  "Veritania's Crest": 250,
  "Fragment of Emptiness": 500,
  "Fragment of Knowledge": 500,
  "Fragment of Shape": 500,
  "Fragment of Terror": 500,
  "Awakening Fragment": 500,
  "Blazing Fragment": 500,
  "Cosmic Fragment": 500,
  "Decaying Fragment": 500,
  "Devouring Fragment": 500,
  "Lonely Fragment": 500,
  "Reality Fragment": 500,
  "Reverent Fragment": 500,
  "Synthesising Fragment": 500,
  "Traumatic Fragment": 500,
  // "Echo of X" - the Atlas Memory boss-access keys, distinct from the "Memory of X" currency
  // above (previously left unmapped pending this disambiguation - poedb prices them separately).
  "Echo of Loneliness": 500,
  "Echo of Reverence": 500,
  "Echo of Trauma": 500,
  "Ritual Splinter": 2,
  "Crescent Splinter": 100,

  // --- Legion splinters (distinct from the emblems below - see LEGION_EMBLEM_COSTS) ---
  "Timeless Karui Splinter": 5,
  "Timeless Eternal Empire Splinter": 5,
  "Timeless Vaal Splinter": 5,
  "Timeless Maraketh Splinter": 8,
  "Timeless Templar Splinter": 8,

  // --- Enshrouding Crystals (Legion mechanic) ---
  "Karui Enshrouding Crystal": 1000,
  "Imperial Enshrouding Crystal": 1000,
  "Vaal Enshrouding Crystal": 1000,
  "Templar Enshrouding Crystal": 1000,
  "Maraketh Enshrouding Crystal": 1000,

  // --- Zorath's Eyes (Abyss mechanic boss keys) ---
  "Zorath's Eye of Authority": 500,
  "Zorath's Eye of Malevolence": 500,
  "Zorath's Eye of the Endless": 500,
  "Zorath's Eye of the Inevitable": 500,

  // --- Allflame Embers ---
  "Allflame Ember of Kulemak": 500,
  "Allflame Ember of Resplendence": 500,
  "Allflame Ember of Propagation": 500,
  "Allflame Ember of Flesh": 500,
  "Allflame Ember of the Wildwood": 350,
  "Allflame Ember of the Ethereal": 350,
  "Allflame Ember of the Gilded": 350,
  "Allflame Ember of Toads": 350,

  // --- Allflame-league Deepwater/misc items ---
  "Dead Man's Sulphur": 1 / 1000,
  "Message in a Bottle": 1000,
  "Exotic Coinage": 25,
  "Burial Medallion": 50,
  "Crystallised Rancour": 125,
  "Wild Crystallised Lifeforce": 1 / 8,
  "Vivid Crystallised Lifeforce": 1 / 8,
  "Primal Crystallised Lifeforce": 1 / 8,

  // --- Ducats (Allflame mechanic - all flat 500) ---
  "Merrick's Ducat": 500,
  "Cyaxan's Ducat": 500,
  "The Genteel's Ducat": 500,
  "Kishara's Ducat": 500,
  "Telesia's Ducat": 500,
  "Tzamoto's Ducat": 500,
  "The Changeling's Ducat": 500,
  "Rotmother's Ducat": 500,
  "Brinehook's Ducat": 500,
  "Katakohi's Ducat": 500,
  "Ukatoa's Ducat": 500,
};

/** Eldritch ichor/ember tiers (35, 50, 75, 200 ascending) - same across both item families. */
const ELDRITCH_TIERS: Readonly<Record<string, number>> = {
  Lesser: 35,
  Greater: 50,
  Grand: 75,
  Exceptional: 200,
};

/** Delve resonators, by the tier word in the name (5, 10, 15, 25 ascending) - same across both
 *  Chaotic and Alchemical resonators. */
const RESONATOR_TIERS: Readonly<Record<string, number>> = {
  Primitive: 5,
  Potent: 10,
  Powerful: 15,
  Prime: 25,
};

/**
 * Essence tier prefix -> gold cost, uniform across every one of the 69 essence names
 * (Whispering/Muttering/.../Deafening Essence of <mod>) and confirmed identical across all 20
 * essence-of-<mod> families on poedb's page - so this single lookup covers the entire category
 * exactly, rather than needing 69 individual entries.
 */
const ESSENCE_TIER_COSTS: Readonly<Record<string, number>> = {
  Whispering: 25,
  Muttering: 35,
  Weeping: 45,
  Wailing: 55,
  Screaming: 65,
  Shrieking: 75,
  Deafening: 75,
};

/** The five "special" league-mechanic essences (Essence of Hysteria/Insanity/Horror/Delirium/
 *  Desolation), which don't follow the tiered-prefix naming above - flat 75 each per poedb. */
const SPECIAL_ESSENCE_COST = 75;

/** Every Delve fossil name (all 25) against its exact poedb cost - grouped by cost, not tier name,
 *  since fossil tiers aren't named the way essence/resonator tiers are. */
const FOSSIL_COSTS: Readonly<Record<string, number>> = Object.fromEntries(
  [
    [30, ["Scorched", "Frigid", "Metallic", "Jagged", "Aberrant", "Pristine", "Dense"]],
    [
      45,
      [
        "Corroded",
        "Prismatic",
        "Aetheric",
        "Serrated",
        "Bound",
        "Opulent",
        "Deft",
        "Lucent",
        "Shuddering",
        "Fundamental",
      ],
    ],
    [100, ["Sanctified", "Gilded", "Faceted", "Bloodstained", "Hollow", "Fractured", "Glyphic", "Tangled"]],
  ].flatMap(([cost, names]) => (names as string[]).map((n) => [`${n} Fossil`, cost as number]))
);

/**
 * Every real Scarab name (see docs/faustus-mapping.md's 115-entry Scarabs section) against its
 * exact poedb cost. poedb's own page lists a handful of scarab names that don't match any real,
 * currently-tradeable scarab (leftover/removed variants) - those are simply omitted here rather
 * than included as dead entries, since goldCostFor only ever looks this map up by a real name.
 */
const SCARAB_COSTS: Readonly<Record<string, number>> = {
  "Abyss Scarab": 75,
  "Abyss Scarab of Crystals": 125,
  "Abyss Scarab of Descending": 125,
  "Abyss Scarab of Multitudes": 100,
  "Abyss Scarab of the Consort": 350,
  "Ambush Scarab": 75,
  "Ambush Scarab of Containment": 350,
  "Ambush Scarab of Discernment": 125,
  "Ambush Scarab of Hidden Compartments": 100,
  "Ambush Scarab of Potency": 100,
  "Anarchy Scarab": 75,
  "Anarchy Scarab of Gigantification": 100,
  "Anarchy Scarab of Partnership": 125,
  "Anarchy Scarab of the Exceptional": 350,
  "Bestiary Scarab": 75,
  "Bestiary Scarab of Duplicating": 125,
  "Bestiary Scarab of the Herd": 100,
  "Betrayal Scarab": 75,
  "Betrayal Scarab of Reinforcements": 100,
  "Betrayal Scarab of the Allflame": 100,
  "Betrayal Scarab of Unbreaking": 125,
  "Beyond Scarab": 75,
  "Beyond Scarab of Haemophilia": 125,
  "Beyond Scarab of Resurgence": 125,
  "Beyond Scarab of the Invasion": 125,
  "Blight Scarab": 75,
  "Blight Scarab of Blooming": 350,
  "Blight Scarab of Invigoration": 350,
  "Blight Scarab of the Blightheart": 125,
  "Breach Scarab of Instability": 125,
  "Breach Scarab of Resonant Cascade": 350,
  "Breach Scarab of the Hive": 75,
  "Breach Scarab of the Incensed Swarm": 350,
  "Breach Scarab of the Marshal": 100,
  "Cartography Scarab of Corruption": 125,
  "Cartography Scarab of Escalation": 75,
  "Cartography Scarab of Risk": 100,
  "Cartography Scarab of the Multitude": 100,
  "Delirium Scarab": 75,
  "Delirium Scarab of Delusions": 125,
  "Delirium Scarab of Mania": 100,
  "Delirium Scarab of Neuroses": 125,
  "Delirium Scarab of Paranoia": 100,
  "Divination Scarab of Pilfering": 125,
  "Divination Scarab of Plenty": 125,
  "Divination Scarab of The Cloister": 75,
  "Domination Scarab": 75,
  "Domination Scarab of Apparitions": 100,
  "Domination Scarab of Evolution": 125,
  "Domination Scarab of Terrors": 350,
  "Essence Scarab": 75,
  "Essence Scarab of Adaptation": 350,
  "Essence Scarab of Ascent": 125,
  "Essence Scarab of Calcification": 350,
  "Essence Scarab of Stability": 100,
  "Expedition Scarab": 75,
  "Expedition Scarab of Archaeology": 125,
  "Expedition Scarab of Infusion": 350,
  "Expedition Scarab of Runefinding": 100,
  "Expedition Scarab of Verisium Powder": 100,
  "Harvest Scarab": 75,
  "Harvest Scarab of Cornucopia": 350,
  "Harvest Scarab of Doubling": 125,
  "Horned Scarab of Awakening": 350,
  "Horned Scarab of Bloodlines": 500,
  "Horned Scarab of Glittering": 350,
  "Horned Scarab of Nemeses": 125,
  "Horned Scarab of Pandemonium": 350,
  "Horned Scarab of Preservation": 500,
  "Horned Scarab of Tradition": 350,
  "Incursion Scarab": 75,
  "Incursion Scarab of Champions": 125,
  "Incursion Scarab of Invasion": 100,
  "Incursion Scarab of Timelines": 350,
  "Influencing Scarab of Hordes": 100,
  "Influencing Scarab of Interference": 125,
  "Influencing Scarab of the Elder": 75,
  "Influencing Scarab of the Shaper": 75,
  "Kalguuran Scarab": 100,
  "Kalguuran Scarab of Enriching": 350,
  "Kalguuran Scarab of Guarded Riches": 125,
  "Kalguuran Scarab of Refinement": 350,
  "Legion Scarab": 75,
  "Legion Scarab of Eternal Conflict": 350,
  "Legion Scarab of Officers": 125,
  "Legion Scarab of Treasures": 125,
  "Ritual Scarab of Abundance": 125,
  "Ritual Scarab of Corpses": 350,
  "Ritual Scarab of Selectiveness": 75,
  "Ritual Scarab of Wisps": 100,
  "Scarab of Adversaries": 75,
  "Scarab of Divinity": 100,
  "Scarab of Monstrous Lineage": 75,
  "Scarab of Radiant Storms": 350,
  "Scarab of Stability": 125,
  "Scarab of the Dextral": 125,
  "Scarab of the Sinistral": 125,
  "Scarab of Wisps": 125,
  "Sulphite Scarab": 75,
  "Sulphite Scarab of Fumes": 125,
  "Titanic Scarab": 75,
  "Titanic Scarab of Legend": 350,
  "Titanic Scarab of Treasures": 125,
  "Torment Scarab": 75,
  "Torment Scarab of Peculiarity": 100,
  "Torment Scarab of Possession": 125,
  "Trarthan Scarab": 75,
  "Trarthan Scarab of Infamy": 100,
  "Trarthan Scarab of Renown": 125,
  "Trarthan Scarab of Surprising Alliances": 350,
  "Ultimatum Scarab": 75,
  "Ultimatum Scarab of Bribing": 100,
  "Ultimatum Scarab of Catalysing": 500,
  "Ultimatum Scarab of Dueling": 350,
  "Ultimatum Scarab of Inscription": 125,
};

/**
 * Divination Card name -> exact poedb cost. Covers the majority of cards poedb's page listed
 * before its content was truncated (its Jewellery/Jewels category cut off partway through); any
 * card not in this map falls back to the wiki's 15-1850 family range, flagged approximate.
 */
const DIVINATION_CARD_COSTS: Readonly<Record<string, number>> = {
  "A Dab of Ink": 250,
  "Akil's Prophecy": 400,
  "Alivia's Grace": 175,
  "Anarchy's Price": 1250,
  "A Note in the Wind": 350,
  "Assassin's Favour": 65,
  "Assassin's Gift": 1850,
  "Astral Protection": 250,
  "Atziri's Arsenal": 200,
  Audacity: 525,
  "Beauty Through Death": 825,
  "Bowyer's Dream": 425,
  "Broken Truce": 175,
  "Cursed Words": 125,
  "Dark Dreams": 500,
  "Dark Temptation": 65,
  Death: 200,
  "Desperate Crusade": 375,
  "Destined to Crumble": 15,
  "Draped in Dreams": 625,
  Duality: 1150,
  "Emperor of Purity": 150,
  "Endless Night": 275,
  "Energy Sword": 500,
  "Etched in Blood": 700,
  "Forbidden Power": 150,
  "From Bone to Ashes": 400,
  "Further Invention": 850,
  "Gift of Asenath": 450,
  Humility: 150,
  "Hunter's Resolve": 75,
  "Immortal Resolve": 225,
  "Imperial Legacy": 55,
  "Judging Voices": 400,
  "Keeper's Corruption": 925,
  "Last Stand": 1150,
  "Lethean Temptation": 475,
  "Light and Truth": 250,
  "Lucky Bastion": 850,
  "Merciless Armament": 350,
  "Might is Right": 150,
  "Misery in Darkness": 450,
  Mitts: 10,
  "Nook's Crown": 925,
  "Poisoned Faith": 550,
  "Pride Before the Fall": 450,
  "Pride of the First Ones": 500,
  "Prometheus' Armoury": 800,
  Rats: 40,
  Rebirth: 475,
  "Reckless Ambition": 275,
  "Sambodhi's Wisdom": 575,
  "The Adventuring Spirit": 75,
  "The Archmage's Right Hand": 150,
  "The Army of Blood": 75,
  "The Astromancer": 1450,
  "The Avenger": 375,
  "The Battle Born": 120,
  "The Bear Woman": 225,
  "The Beast": 175,
  "The Betrayal": 150,
  "The Blazing Fire": 55,
  "The Body": 125,
  "The Brawny Battle Mage": 375,
  "The Carrion Crow": 25,
  "The Catch": 925,
  "The Celestial Justicar": 225,
  "The Chains that Bind": 70,
  "The Chosen": 1250,
  "The Coming Storm": 150,
  "The Conduit": 250,
  "The Dapper Prodigy": 150,
  "The Darkest Dream": 325,
  "The Dark Mage": 200,
  "The Deep Ones": 400,
  "The Demoness": 65,
  "The Endless Darkness": 925,
  "The Enforcer": 1100,
  "The Enthusiasts": 300,
  "The Escape": 250,
  "The Ethereal": 250,
  "The Fathomless Depths": 175,
  "The Fletcher": 150,
  "The Flora's Gift": 25,
  "The Formless Sea": 275,
  "The Fox in the Brambles": 225,
  "The Gentleman": 200,
  "The Gladiator": 120,
  "The Golden Era": 175,
  "The Greatest Intentions": 1350,
  "The Harvester": 40,
  "The Hermit": 35,
  "The Hive of Knowledge": 800,
  "The Incantation": 200,
  "The Inoculated": 105,
  "The Insane Cat": 1850,
  "The Insatiable": 175,
  "The Jester": 275,
  "The Jeweller's Boon": 125,
  "The Journalist": 55,
  "The King's Blade": 15,
  "The King's Heart": 275,
  "The Last One Standing": 850,
  "The Last Supper": 1025,
  "The Lich": 125,
  "The Long Watch": 550,
  "The Lord of Celebration": 225,
  "The Lunaris Priestess": 90,
  "The Mercenary": 175,
  "The Oath": 175,
  "The Offering": 275,
  "The Old Man": 1600,
  "The Pack Leader": 175,
  "The Pact": 300,
  "The Poet": 150,
  "The Porcupine": 125,
  "The Price of Loyalty": 1600,
  "The Queen": 400,
  "The Rabid Rhoa": 125,
  "The Road to Power": 350,
  "The Sacrifice": 650,
  "The Scarred Meadow": 35,
  "The Scavenger": 150,
  "The Shepherd's Sandals": 350,
  "The Shieldbearer": 925,
  "The Siren": 250,
  "The Soul": 900,
  "The Spoiled Prince": 225,
  "The Stormcaller": 110,
  "The Sun": 60,
  "The Throne": 400,
  "The Tower": 100,
  "The Traitor": 200,
  "The Twins": 125,
  "The Tyrant": 275,
  "The Undisputed": 825,
  "The Vast": 1200,
  "The Visionary": 75,
  "The Warlord": 250,
  "The Watcher": 125,
  "The Web": 95,
  "The Wedding Gift": 550,
  "The White Knight": 650,
  "The Whiteout": 275,
  "The Wind": 275,
  "The Wolf's Shadow": 125,
  "The Wolven King's Bite": 275,
  "The Wolverine": 200,
  "The World Eater": 925,
  "Thunderous Skies": 65,
  "Toxic Tidings": 375,
  Tranquillity: 950,
  Unchained: 275,
  Vanity: 225,
  "Vile Power": 175,
  "Who Asked": 1000,
  "A Familiar Call": 1150,
  "A Modest Request": 475,
  "A Mother's Parting Gift": 200,
  Apocalypse: 700,
  "A Stone Perfected": 425,
  "Azyran's Reward": 300,
  Bijoux: 350,
  "Blind Venture": 150,
  "Broken Promises": 650,
  "Brotherhood in Exile": 375,
  "Burning Blood": 1050,
  "Call to the First Ones": 175,
  "Choking Guilt": 1450,
  "Deadly Joy": 725,
  "Divine Justice": 1850,
  "Dying Light": 650,
  "Father's Love": 1350,
  "Fire Of Unknown Origin": 925,
  Friendship: 550,
  "Glimmer of Hope": 65,
  Heterochromia: 175,
  Hope: 150,
  Hubris: 120,
  "Hunter's Reward": 325,
  "Imperfect Memories": 650,
  "Lachrymal Necrosis": 250,
  "Lantador's Lost Love": 35,
  "Lonely Warrior": 1250,
  "Love Through Ice": 1350,
  "Luminous Trove": 575,
  "Lysah's Respite": 150,
  Matryoshka: 600,
  "Mawr Blaidd": 350,
  "One Last Score": 1000,
  "Peaceful Moments": 350,
  Perfection: 650,
  Prosperity: 55,
  "Reflection of the Heart": 670,
  Remembrance: 650,
  "Shard of Fate": 125,
  "Silence and Frost": 625,
  "Squandered Prosperity": 675,
  "Struck by Lightning": 95,
  "The Academic": 400,
  "The Apothecary": 1100,
  "The Awakened": 925,
  "The Brittle Emperor": 450,
  "The Cache": 100,
  "The Celestial Stone": 700,
  "The Craving": 500,
  "The Cursed King": 250,
  "The Deceiver": 175,
  "The Demon": 1850,
  "The Destination": 925,
  "The Doctor": 925,
  "The Dungeon Master": 300,
  "The Endurance": 125,
  "The Eternal War": 950,
  "The Eye of the Dragon": 575,
  "The Feast": 150,
  "The Fiend": 1350,
  "The Forgotten Treasure": 325,
  "The Forsaken": 150,
  "The Garish Power": 500,
  "The Gulf": 650,
  "The Last Laugh": 650,
  "The Life Thief": 575,
  "The Lord in Black": 200,
  "The Lover": 10,
  "The Mayor": 425,
  "The Metalsmith's Gift": 20,
  "The Mind's Eyes": 275,
  "The Mountain": 125,
  "The Offspring": 325,
  "The One That Got Away": 1450,
  "The One With All": 150,
  "The Opulent": 55,
  "The Penitent": 115,
  "The Polymath": 375,
  "The Price of Devotion": 1850,
  "The Primordial": 200,
  "The Prince of Darkness": 375,
  "The Return of the Rat": 200,
  "The Risk": 125,
  "The Ruthless Ceinture": 150,
  "The Samurai's Eye": 525,
  "The Sigil": 90,
  "The Spark and the Flame": 250,
  "The Standoff": 110,
  "The Strategist": 700,
  "The Sword King's Salute": 45,
  "The Thaumaturgist": 450,
  "The Tumbleweed": 725,
  "The Unexpected Prize": 275,
  "The Warden": 70,
  "The Wretched": 125,
  "Thirst for Knowledge": 90,
  "Turn the Other Cheek": 250,
  "Void of the Elements": 875,
  "When Currents Blaze": 875,
  "Winter's Embrace": 600,
  "Abandoned Wealth": 275,
  Acclimatisation: 125,
  "Alluring Bounty": 375,
  "Ambitious Obsession": 1850,
  "A Sea of Blue": 90,
  "Brother's Gift": 600,
  "Brother's Stash": 600,
  "Cartographer's Delight": 125,
  "Chaotic Disposition": 125,
  Checkmate: 325,
  "Coveted Possession": 150,
  "Darker Half": 750,
  Dementophobia: 500,
  "Demigod's Wager": 225,
  Disdain: 300,
  "Divine Beauty": 275,
  "Echoes of Love": 275,
  "Emperor's Luck": 10,
  "Ever-Changing": 175,
  "Harmony of Souls": 375,
  History: 1850,
  "House of Mirrors": 1850,
  "I See Brothers": 775,
  Loyalty: 20,
  "Lucky Connections": 95,
  "Lucky Deck": 350,
  Monochrome: 275,
  "No Traces": 150,
  Outfoxed: 1000,
  "Parasitic Passengers": 250,
  "Rain of Chaos": 5,
  "Runic Luck": 550,
  "Seven Years Bad Luck": 550,
  "Society's Remorse": 125,
  "The Cacophony": 375,
  "The Catalyst": 25,
  "The Finishing Touch": 275,
  "The Fishmonger": 825,
  "The Fool": 125,
  "The Fortunate": 175,
  "The Gemcutter": 125,
  "The Heroic Shot": 150,
  "The Hoarder": 150,
  "The Innocent": 200,
  "The Inventor": 105,
  "The Rusted Bard": 425,
  "The Journey": 225,
  "The Lake": 1500,
  "The Long Con": 600,
  "The Master Artisan": 125,
  "The Rabbit's Foot": 575,
  "The Saint's Treasure": 200,
  "The Scholar": 15,
  "The Scout": 325,
  "The Seeker": 325,
  "The Sephirot": 325,
  "The Side Quest": 250,
  "The Slumbering Beast": 500,
  "The Survivalist": 90,
  "The Tinkerer's Table": 350,
  "The Tireless Extractor": 70,
  "The Transformation": 325,
  "The Union": 175,
  "The Wrath": 85,
  "Three Faces in the Dark": 25,
  "Three Voices": 55,
  "Underground Forest": 350,
  "Unrequited Love": 1450,
  "Vinia's Token": 60,
  "A Chilling Wind": 325,
  "Bound by Flame": 325,
  "Deathly Designs": 375,
  "Desecrated Virtue": 775,
  "Dialla's Subjugation": 175,
  "Doryani's Epiphany": 450,
  "Dying Anguish": 150,
  "Gemcutter's Mercy": 450,
  "Gemcutter's Promise": 85,
  "Gift of the Gemling Queen": 150,
  "Grave Knowledge": 125,
  Home: 475,
  "Terrible Secret of Space": 1250,
  "The Artist": 675,
  "The Bitter Blossom": 450,
  "The Blessing of Moosh": 375,
  "The Bones": 275,
  "The Cataclysm": 150,
  "The Doppelganger": 35,
  "The Dragon's Heart": 675,
  "The Emptiness": 775,
  "The Enlightened": 525,
  "The Fox": 150,
  "The Hook": 475,
  "The Magma Crab": 275,
  "The Miracle": 750,
  "The Realm": 200,
  "The Rite of Elements": 150,
  "The Skeleton": 125,
  "The Summoner": 110,
  "The Wilted Rose": 150,
  "Volatile Power": 110,
  "Wealth and Power": 675,
  "A Fate Worse Than Death": 525,
  "Altered Perception": 725,
  "Avian Pursuit": 500,
  "Azure Rage": 125,
  "Boon of Justice": 85,
  "Boundless Realms": 125,
  "Buried Treasure": 250,
  "Cameria's Cut": 125,
  "Divine Shard": 250,
  "Eternal Bonds": 725,
  "Guardian's Challenge": 175,
  "Her Mask": 70,
  "Justified Ambition": 275,
  "Last Hope": 110,
  "Left to Fate": 125,
  "Lingering Remnants": 200,
  "Lost Worlds": 80,
  "Man With Bear": 250,
  "More is Never Enough": 30,
  "Rain Tempter": 55,
  "Rebirth and Renewal": 250,
  "Sambodhi's Vow": 125,
  "Scholar of the Seas": 150,
  "Something Dark": 250,
  "The Arena Champion": 55,
  "The Card Sharp": 275,
  "The Deal": 200,
  "The Dreamland": 200,
  "The Easy Stroll": 175,
  "The Eldritch Decay": 250,
  "The Encroaching Darkness": 200,
  "The Explorer": 85,
  "The Eye of Terror": 1150,
  "The Forbidden Fruit": 1150,
  "The Price of Prescience": 375,
  "The Price of Protection": 175,
  "The Professor": 400,
  "The Silly Boy": 700,
  "The Surveyor": 125,
  "The Trial": 115,
  "The Twilight Moon": 275,
  "The Wolf's Legacy": 150,
  "Treasure Hunter": 225,
  Triskaidekaphobia: 200,
  "Earth Drinker": 175,
  "Pearls Before Swine": 1000,
  "Succor of the Sinless": 775,
  "The Damned": 775,
  "The Dragon": 110,
  "The Drunken Aristocrat": 150,
  "The Hunger": 250,
  "The Progeny of Lunaris": 725,
  "The Shortcut": 425,
  "The Surgeon": 125,
  "The Witch": 40,
  "A Dusty Memory": 325,
  "Alone in the Darkness": 100,
  "Arrogance of the Vaal": 250,
  "Auspicious Ambitions": 1150,
  "Baited Expectations": 275,
  "Boon of the First Ones": 225,
  "Brush, Paint and Palette": 250,
  "Chasing Risk": 350,
  "Costly Curio": 275,
  "Council of Cats": 350,
  Damnation: 1350,
  "Doedre's Madness": 50,
  "Eldritch Perfection": 575,
  "Fateful Meeting": 1150,
  "Haunting Shadows": 225,
  "Jack in the Box": 125,
  "Magnum Opus": 575,
  Prejudice: 150,
  Temperance: 525,
  "The Admirer": 175,
  "The Aesthete": 120,
  "The Aspirant": 925,
  "The Breach": 350,
  "The Calling": 125,
  "The Dreamer": 425,
  "The Everlasting": 775,
  "The Forward Gaze": 200,
  "The Gambler": 125,
  "The Hale Heart": 650,
  "The Immortal": 825,
  "The Leviathan": 775,
  "The Lion": 125,
  "The Mad King": 300,
  "The Messenger": 300,
  "The Nurse": 450,
  "The Patient": 225,
  "The Undaunted": 200,
  "The Valkyrie": 125,
  "The Void": 125,
  "The Wolf": 125,
  "Time-Lost Relic": 105,
};

/** Every Oil name against its exact poedb cost. */
const OIL_COSTS: Readonly<Record<string, number>> = {
  "Clear Oil": 25,
  "Sepia Oil": 25,
  "Amber Oil": 25,
  "Verdant Oil": 50,
  "Teal Oil": 50,
  "Azure Oil": 50,
  "Indigo Oil": 75,
  "Violet Oil": 75,
  "Crimson Oil": 75,
  "Black Oil": 100,
  "Opalescent Oil": 125,
  "Silver Oil": 125,
  "Golden Oil": 125,
  "Tainted Oil": 500,
  "Reflective Oil": 500,
  "Prismatic Oil": 500,
};

/** Every Catalyst name against its exact poedb cost. */
const CATALYST_COSTS: Readonly<Record<string, number>> = {
  "Intrinsic Catalyst": 25,
  "Turbulent Catalyst": 25,
  "Imbued Catalyst": 25,
  "Abrasive Catalyst": 25,
  "Noxious Catalyst": 25,
  "Tempering Catalyst": 50,
  "Fertile Catalyst": 50,
  "Prismatic Catalyst": 50,
  "Accelerating Catalyst": 50,
  "Unstable Catalyst": 50,
  "Tainted Catalyst": 150,
  "Sinistral Catalyst": 150,
  "Dextral Catalyst": 150,
};

/** Every Omen name against its exact poedb cost. */
const OMEN_COSTS: Readonly<Record<string, number>> = {
  "Omen of Return": 25,
  "Omen of Death-dancing": 25,
  "Omen of Refreshment": 25,
  "Omen of the Soul Devourer": 25,
  "Omen of Adrenaline": 25,
  "Omen of Death's Door": 50,
  "Omen of Brilliance": 50,
  "Omen of Amelioration": 50,
  "Omen of the Jeweller": 50,
  "Omen of Trichromatism": 50,
  "Omen of Connections": 125,
  "Omen of Fortune": 125,
};

/**
 * Every Tattoo name against its exact poedb cost - the Dexterity/Intelligence/Strength/Special
 * tribe tattoos plus the tiered "Loyalty"/"Honoured"/"Journey"/"Forbidden" variants.
 */
const TATTOO_COSTS: Readonly<Record<string, number>> = {
  "Tattoo of the Arohongui Moonwarden": 25,
  "Tattoo of the Arohongui Scout": 25,
  "Tattoo of the Arohongui Warrior": 25,
  "Loyalty Tattoo of Ikiaho": 100,
  "Tattoo of the Arohongui Makanga": 100,
  "Tattoo of the Ramako Scout": 25,
  "Tattoo of the Ramako Archer": 25,
  "Tattoo of the Ramako Sniper": 25,
  "Tattoo of the Ramako Fleetfoot": 50,
  "Tattoo of the Ramako Shaman": 50,
  "Loyalty Tattoo of Ahuana": 100,
  "Tattoo of the Ramako Makanga": 100,
  "Tattoo of the Tawhoa Naturalist": 25,
  "Tattoo of the Tawhoa Scout": 25,
  "Tattoo of the Tawhoa Herbalist": 50,
  "Tattoo of the Tawhoa Makanga": 100,
  "Tattoo of the Tasalio Tideshifter": 25,
  "Tattoo of the Tasalio Warrior": 50,
  "Tattoo of the Tasalio Scout": 50,
  "Loyalty Tattoo of Rakiata": 100,
  "Tattoo of the Arohongui Warmonger": 50,
  "Tattoo of the Arohongui Shaman": 50,
  "Tattoo of the Hinekora Warrior": 25,
  "Tattoo of the Hinekora Deathwarden": 25,
  "Tattoo of the Hinekora Shaman": 25,
  "Tattoo of the Hinekora Storyteller": 50,
  "Tattoo of the Hinekora Warmonger": 50,
  "Loyalty Tattoo of Tawhanuku": 100,
  "Tattoo of the Hinekora Makanga": 100,
  "Tattoo of the Tawhoa Warrior": 25,
  "Tattoo of the Tawhoa Shaman": 50,
  "Loyalty Tattoo of Maata": 100,
  "Tattoo of the Rongokurai Turtle": 50,
  "Tattoo of the Tasalio Shaman": 25,
  "Tattoo of the Tasalio Makanga": 100,
  "Tattoo of the Kitava Heart Eater": 50,
  "Tattoo of the Valako Stormrider": 25,
  "Tattoo of the Valako Scout": 25,
  "Tattoo of the Valako Warrior": 25,
  "Tattoo of the Valako Shaman": 50,
  "Loyalty Tattoo of Kiloava": 100,
  "Tattoo of the Valako Makanga": 100,
  "Tattoo of the Ngamahu Firewalker": 25,
  "Tattoo of the Ngamahu Shaman": 25,
  "Tattoo of the Ngamahu Warrior": 25,
  "Tattoo of the Ngamahu Warmonger": 50,
  "Tattoo of the Ngamahu Woodcarver": 50,
  "Loyalty Tattoo of Kaom": 100,
  "Tattoo of the Ngamahu Makanga": 100,
  "Tattoo of the Rongokurai Warrior": 25,
  "Tattoo of the Rongokurai Brute": 25,
  "Tattoo of the Rongokurai Goliath": 25,
  "Tattoo of the Rongokurai Guard": 50,
  "Loyalty Tattoo of Kahuturoa": 100,
  "Tattoo of the Rongokurai Makanga": 100,
  "Tattoo of the Tasalio Bladedancer": 25,
  "Tattoo of the Kitava Blood Drinker": 25,
  "Tattoo of the Kitava Rebel": 25,
  "Tattoo of the Kitava Warrior": 25,
  "Tattoo of the Kitava Shaman": 50,
  "Loyalty Tattoo of Utula": 100,
  "Tattoo of the Kitava Makanga": 100,
  "Tattoo of the Tukohama Shaman": 25,
  "Tattoo of the Tukohama Warrior": 25,
  "Tattoo of the Tukohama Brawler": 25,
  "Tattoo of the Tukohama Warmonger": 50,
  "Tattoo of the Tukohama Warcaller": 50,
  "Loyalty Tattoo of Akoya": 100,
  "Tattoo of the Tukohama Makanga": 100,
  "Tattoo of the Valako Shieldbearer": 50,
  "Honoured Tattoo of the Dove": 125,
  "Honoured Tattoo of the Sky": 125,
  "Honoured Tattoo of the Tuatara": 125,
  "Honoured Tattoo of the Pillager": 125,
  "Honoured Tattoo of the Turtle": 125,
  "Honoured Tattoo of the Oak": 125,
  "Honoured Tattoo of the Hatungo": 125,
  "Honoured Tattoo of the Flock": 125,
  "Honoured Tattoo of the Warlord": 125,
  "Honoured Tattoo of the Mountain": 125,
  "Honoured Tattoo of the Pa": 125,
  "Honoured Tattoo of the Hunter": 125,
  "Honoured Tattoo of the Barbarian": 125,
  "Honoured Tattoo of the Berserker": 125,
  "Honoured Tattoo of the Wise": 125,
  "Honoured Tattoo of the Storm": 125,
  "Honoured Tattoo of the Flood": 125,
  "Ancestral Tattoo of Bloodlines": 125,
  "Honoured Tattoo of the Makanga": 125,
  "Journey Tattoo of the Body": 125,
  "Journey Tattoo of the Mind": 125,
  "Journey Tattoo of the Soul": 125,
  "Journey Tattoo of Makanui": 125,
  "Forbidden Tattoo of the Ranger": 125,
  "Forbidden Tattoo of the Duelist": 125,
  "Forbidden Tattoo of the Marauder": 125,
  "Forbidden Tattoo of the Templar": 125,
  "Forbidden Tattoo of the Witch": 125,
  "Forbidden Tattoo of the Shadow": 125,
  "Forbidden Tattoo of the Scion": 125,
};

/** Every named Delirium Orb against its exact poedb cost. */
const DELIRIUM_ORB_COSTS: Readonly<Record<string, number>> = {
  "Delirium Orb": 250,
  "Blacksmith's Delirium Orb": 75,
  "Armoursmith's Delirium Orb": 75,
  "Jeweller's Delirium Orb": 75,
  "Fine Delirium Orb": 100,
  "Diviner's Delirium Orb": 150,
  "Cartographer's Delirium Orb": 175,
  "Whispering Delirium Orb": 175,
  "Singular Delirium Orb": 175,
  "Thaumaturge's Delirium Orb": 225,
  "Abyssal Delirium Orb": 225,
  "Obscured Delirium Orb": 225,
  "Fragmented Delirium Orb": 225,
  "Fossilised Delirium Orb": 225,
  "Timeless Delirium Orb": 225,
  "Blighted Delirium Orb": 225,
  "Kalguuran Delirium Orb": 75,
  "Skittering Delirium Orb": 250,
  "Primal Delirium Orb": 75,
  "Imperial Delirium Orb": 75,
  "Challenging Delirium Orb": 75,
};

/** Legion emblems - NOT a uniform value across tiers, unlike most other tiered families. */
const LEGION_EMBLEM_COSTS: Readonly<Record<string, number>> = {
  "Timeless Karui Emblem": 500,
  "Timeless Maraketh Emblem": 750,
  "Timeless Eternal Emblem": 500,
  "Timeless Templar Emblem": 750,
  "Timeless Vaal Emblem": 500,
};

/** Runegrafts - flat 500 except the Angler variant. */
const RUNEGRAFT_ANGLER_COST = 5000;
const RUNEGRAFT_DEFAULT_COST = 500;

/** Vaal fragments (Atziri sacrifice pieces and their Uber Atziri "Mortal" counterparts). */
const VAAL_FRAGMENT_COSTS: Readonly<Record<string, number>> = {
  "Sacrifice at Dusk": 15,
  "Sacrifice at Noon": 30,
  "Sacrifice at Midnight": 75,
  "Sacrifice at Dawn": 20,
  "Mortal Grief": 40,
  "Mortal Ignorance": 75,
  "Mortal Rage": 190,
  "Mortal Hope": 50,
};

/** The Labyrinth's four Goddess offerings. */
const GODDESS_OFFERING_COSTS: Readonly<Record<string, number>> = {
  "Offering to the Goddess": 30,
  "Tribute to the Goddess": 180,
  "Gift to the Goddess": 180,
  "Dedication to the Goddess": 180,
};

const DIVINATION_CARD_ID_PREFIX = "Metadata/Items/DivinationCards/";

/**
 * Cost for one exchange-tradeable item by display name, or undefined when neither source covers
 * it at all. Name-pattern rules only cover families where the tier is genuinely recoverable from
 * the name (Eldritch ichor/ember, resonators, essences); everything else either matches one of the
 * exact per-name tables above or falls back to a flagged family estimate - never a fabricated
 * per-item guess.
 *
 * `id` is the item's GGG metadata id (lib/faustus.ts's FAUSTUS_NAME_TO_ID value for this name) -
 * needed only to recognise Divination Cards, whose flavour-text names can't be matched by a pattern.
 * Optional so this stays testable/callable on a name alone for every other family.
 */
export function goldCostFor(name: string, id?: string): GoldCost | undefined {
  if (id?.startsWith(DIVINATION_CARD_ID_PREFIX)) {
    const cardCost = DIVINATION_CARD_COSTS[name];
    return cardCost !== undefined ? exact(cardCost) : approx(200, "Divination cards range 15-1850 gold per card");
  }

  const exactCost = EXACT_COSTS[name];
  if (exactCost !== undefined) return exact(exactCost);

  const scarabCost = SCARAB_COSTS[name];
  if (scarabCost !== undefined) return exact(scarabCost);

  const fossilCost = FOSSIL_COSTS[name];
  if (fossilCost !== undefined) return exact(fossilCost);

  if (/^(Lesser|Greater|Grand|Exceptional) Eldritch (Ichor|Ember)$/.test(name)) {
    return exact(ELDRITCH_TIERS[name.split(" ")[0]]);
  }
  if (/^(Primitive|Potent|Powerful|Prime) (Alchemical|Chaotic) Resonator$/.test(name)) {
    return exact(RESONATOR_TIERS[name.split(" ")[0]]);
  }
  const essenceTierCost = ESSENCE_TIER_COSTS[name.split(" ")[0]];
  if (essenceTierCost !== undefined && name.includes("Essence of ")) return exact(essenceTierCost);
  if (name.startsWith("Essence of ")) return exact(SPECIAL_ESSENCE_COST);

  const oilCost = OIL_COSTS[name];
  if (oilCost !== undefined) return exact(oilCost);

  const catalystCost = CATALYST_COSTS[name];
  if (catalystCost !== undefined) return exact(catalystCost);

  const omenCost = OMEN_COSTS[name];
  if (omenCost !== undefined) return exact(omenCost);

  const tattooCost = TATTOO_COSTS[name];
  if (tattooCost !== undefined) return exact(tattooCost);

  const deliriumOrbCost = DELIRIUM_ORB_COSTS[name];
  if (deliriumOrbCost !== undefined) return exact(deliriumOrbCost);

  const legionEmblemCost = LEGION_EMBLEM_COSTS[name];
  if (legionEmblemCost !== undefined) return exact(legionEmblemCost);

  const vaalFragmentCost = VAAL_FRAGMENT_COSTS[name];
  if (vaalFragmentCost !== undefined) return exact(vaalFragmentCost);

  const goddessOfferingCost = GODDESS_OFFERING_COSTS[name];
  if (goddessOfferingCost !== undefined) return exact(goddessOfferingCost);

  if (name.includes("Runegraft")) {
    return exact(name.includes("the Angler") ? RUNEGRAFT_ANGLER_COST : RUNEGRAFT_DEFAULT_COST);
  }
  if (name.endsWith(" Astrolabe")) return exact(1000);

  return undefined;
}
