/**
 * Regenerates lib/disenchant-values.ts: each unique's base Thaumaturgic Dust value for Kingsmarch
 * disenchanting. Run it again when a league adds uniques or changes dust values - not part of the
 * running app.
 *
 * Source: poedb's Kingsmarch page, Disenchant tab (https://poedb.tw/us/Kingsmarch#Disenchant). It's
 * the only source found: RePoE's uniques.json has no dust value. The table's columns are name, base
 * value, value at ilvl 84 and value at ilvl 84 q20; only the base value is kept, since the rest
 * follow from lib/dust.ts's formula (checked here: every ilvl-84 column equals value × 2000).
 * Rows poedb strikes through (<del>, removed from the game) are skipped.
 *
 *   npx tsx scripts/generate-disenchant-values.ts           # print a summary
 *   npx tsx scripts/generate-disenchant-values.ts --write   # write lib/disenchant-values.ts
 */
import fs from "node:fs";
import path from "node:path";

const POEDB_URL = "https://poedb.tw/us/Kingsmarch";
const USER_AGENT = "poe-flipper/0.1.0 (personal, non-commercial; unaffiliated with GGG)";
const OUT_PATH = path.join(__dirname, "..", "lib", "disenchant-values.ts");

// A fraction of today's 1,510 rows - fewer means the page layout changed and the parse broke.
const MIN_EXPECTED_ROWS = 1000;

function decodeEntities(text: string): string {
  return text
    .replace(/&#0?39;|&apos;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");
}

interface ParseResult {
  values: Map<string, number>;
  removed: string[];
  total: number;
}

function parseDisenchantTable(html: string): ParseResult {
  const start = html.indexOf('id="Disenchant"');
  if (start === -1) throw new Error("No Disenchant tab on poedb's Kingsmarch page");
  const body = html.slice(html.indexOf("<tbody", start), html.indexOf("</table>", start));
  const rows = body.split("<tr>").slice(1);
  const values = new Map<string, number>();
  const removed: string[] = [];
  for (const row of rows) {
    const m = row.match(/^<td>(<del>)?<a[^>]*>([^<]+)<\/a>(?:<\/del>)?<\/td><td>([\d.]+)<\/td><td>(\d+)<\/td>/);
    if (!m) throw new Error(`Unrecognized Disenchant row: ${row.slice(0, 200)}`);
    const name = decodeEntities(m[2]).trim();
    const value = Number(m[3]);
    if (Math.abs(value * 2000 - Number(m[4])) > 1) {
      throw new Error(`${name}: ilvl-84 column ${m[4]} isn't value × 2000 - the formula in lib/dust.ts may be out of date`);
    }
    if (m[1]) {
      removed.push(name);
      continue;
    }
    if (values.has(name) && values.get(name) !== value) throw new Error(`${name} listed twice with different values`);
    values.set(name, value);
  }
  if (values.size < MIN_EXPECTED_ROWS) throw new Error(`Only ${values.size} rows parsed - poedb's layout may have changed`);
  return { values, removed, total: rows.length };
}

function formatFile(values: Map<string, number>): string {
  const entries = [...values.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  const lines = entries.map(([name, value]) => `  ${JSON.stringify(name)}: ${value},`).join("\n");
  return `/**
 * Each unique's base Thaumaturgic Dust value for Kingsmarch disenchanting, by name - generated by
 * scripts/generate-disenchant-values.ts from poedb's Kingsmarch page (Disenchant tab). Do not
 * hand-edit; re-run the generator instead. lib/dust.ts turns a value into dust for an item level.
 */
export const DISENCHANT_VALUES: Readonly<Record<string, number>> = {
${lines}
};
`;
}

async function main() {
  const write = process.argv.includes("--write");
  const res = await fetch(POEDB_URL, { headers: { "User-Agent": USER_AGENT } });
  if (!res.ok) throw new Error(`poedb request failed (${res.status})`);
  const { values, removed, total } = parseDisenchantTable(await res.text());
  console.log(`${total} rows in poedb's Disenchant table; ${values.size} kept, ${removed.length} removed from the game (${removed.join(", ") || "none"}).`);

  const content = formatFile(values);
  if (!write) {
    console.log("Pass --write to write lib/disenchant-values.ts.");
    return;
  }
  const current = fs.existsSync(OUT_PATH) ? fs.readFileSync(OUT_PATH, "utf8").replace(/\r\n/g, "\n") : "";
  if (current === content) {
    console.log("lib/disenchant-values.ts already up to date.");
  } else {
    fs.writeFileSync(OUT_PATH, content);
    console.log("Wrote lib/disenchant-values.ts.");
  }
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
